# Generated by Django 5.2.4 on 2026-07-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.clinical.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0002_patient_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvanceDirective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("directive_type", models.CharField(max_length=160)),
                ("summary", models.TextField()),
                (
                    "document",
                    models.FileField(blank=True, upload_to="advance-directives/", validators=[apps.clinical.models.validate_clinical_file]),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="advance_directives", to="patients.patient"
                    ),
                ),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("substance", models.CharField(max_length=200)),
                ("reaction", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("LIFE_THREATENING", "Life threatening"),
                        ],
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("source_system", models.CharField(blank=True, max_length=120)),
                ("external_id", models.CharField(blank=True, max_length=160)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allergies", to="patients.patient"),
                ),
                ("recorded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["substance"],
            },
        ),
        migrations.CreateModel(
            name="CarePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("ON_HOLD", "On hold"), ("COMPLETED", "Completed")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("goals", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("source_system", models.CharField(blank=True, max_length=120)),
                ("external_id", models.CharField(blank=True, max_length=160)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="authored_care_plans", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="care_plans", to="patients.patient"),
                ),
            ],
            options={
                "ordering": ["-starts_on", "title"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="clinical-documents/", validators=[apps.clinical.models.validate_clinical_file])),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("retention_until", models.DateField(blank=True, null=True)),
                ("source_system", models.CharField(blank=True, max_length=120)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="clinical_documents", to="patients.patient"
                    ),
                ),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=64)),
                ("code_system", models.CharField(blank=True, max_length=160)),
                ("display", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RESOLVED", "Resolved"), ("INACTIVE", "Inactive")], default="ACTIVE", max_length=16
                    ),
                ),
                ("diagnosed_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("source_system", models.CharField(blank=True, max_length=120)),
                ("external_id", models.CharField(blank=True, max_length=160)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="diagnoses", to="patients.patient"),
                ),
                ("recorded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["display"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("relationship", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("authorized_for_updates", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emergency_contacts", to="patients.patient"
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="WoundRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("length_cm", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("width_cm", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="wound-records/", validators=[apps.clinical.models.validate_clinical_file]),
                ),
                ("recorded_at", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wound_records", to="patients.patient"),
                ),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="VitalThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vital_type",
                    models.CharField(
                        choices=[
                            ("BLOOD_PRESSURE", "Blood pressure"),
                            ("HEART_RATE", "Heart rate"),
                            ("OXYGEN", "Oxygen saturation"),
                            ("TEMPERATURE", "Temperature"),
                            ("WEIGHT", "Weight"),
                            ("GLUCOSE", "Blood glucose"),
                        ],
                        max_length=24,
                    ),
                ),
                ("minimum", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("maximum", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("secondary_minimum", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("secondary_maximum", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                (
                    "severity",
                    models.CharField(choices=[("WARNING", "Warning"), ("CRITICAL", "Critical")], default="WARNING", max_length=12),
                ),
                ("consecutive_readings", models.PositiveSmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("configured_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vital_thresholds", to="patients.patient"),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("patient", "vital_type"), name="unique_patient_vital_threshold")],
            },
        ),
    ]
