# Generated by Django 5.2.4 on 2026-07-16 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BLOOD_PRESSURE", "Blood pressure"),
                            ("HEART_RATE", "Heart rate"),
                            ("OXYGEN", "Oxygen saturation"),
                            ("TEMPERATURE", "Temperature"),
                            ("WEIGHT", "Weight"),
                            ("GLUCOSE", "Blood glucose"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "secondary_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Diastolic value for blood pressure",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(max_length=24)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("note", models.TextField(blank=True)),
                ("client_reference", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vital_records", to="patients.patient"),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_vitals", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
