# Generated by Django 5.2.4 on 2026-07-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecord",
            name="external_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="vitalrecord",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vitalrecord",
            name="source_system",
            field=models.CharField(default="Haven", max_length=120),
        ),
    ]
