import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, BellRing, Building2, RefreshCw, Users } from 'lucide-react'
import { getAdminOverview, retryNotificationDelivery } from '../lib/api'
import type { ApiUser, CaregiverAvailability, EscalationPolicy, NotificationDelivery, Session } from '../lib/types'
import { PageHeader } from '../components/PageHeader'

export default function AdminView({ session, notify }: { session: Session; notify: (message: string) => void }) {
  const [users, setUsers] = useState<ApiUser[]>([])
  const [policies, setPolicies] = useState<EscalationPolicy[]>([])
  const [deliveries, setDeliveries] = useState<NotificationDelivery[]>([])
  const [availability, setAvailability] = useState<CaregiverAvailability[]>([])
  const load = useCallback(() => getAdminOverview(session.token).then((data) => { setUsers(data.users); setPolicies(data.policies); setDeliveries(data.deliveries); setAvailability(data.availability) }), [session.token])
  useEffect(() => { load() }, [load])
  return <><PageHeader eyebrow="ORGANIZATION OVERSIGHT" title="Administration" description="Staff roles, availability, configurable escalation chains, and notification dead-letter handling." action={<button className="secondary-button" onClick={load}><RefreshCw />Refresh</button>} /><div className="admin-grid"><section className="main-card clinical-section"><h3><Users />Staff & permissions</h3>{users.map((user) => <article key={user.id}><span className="avatar avatar-sarah">{user.display_name.slice(0, 2).toUpperCase()}</span><span><strong>{user.display_name}</strong><small>{user.role} · {user.email} · {user.is_active ? 'Active' : 'Disabled'}</small></span></article>)}<h3><Users />Availability</h3>{availability.map((item) => <article key={item.id}><span><strong>{item.caregiver_name}</strong><small>{item.available ? 'Available' : 'Unavailable'} · {new Date(item.starts_at).toLocaleString()}–{new Date(item.ends_at).toLocaleString()}</small></span></article>)}</section><section className="main-card clinical-section"><h3><Building2 />Escalation policies</h3>{policies.map((policy) => <article key={policy.id}><BellRing /><span><strong>{policy.name}{policy.is_default ? ' · Default' : ''}</strong>{policy.steps.map((step) => <small key={step.id}>Level {step.level}: {step.channel} after {step.delay_minutes} min → {step.recipient_roles.join(', ') || 'assigned recipient'}</small>)}</span></article>)}{!policies.length && <p>Create policies through the documented organization API before pilot.</p>}</section></div><section className="main-card recent-readings"><div className="subsection-heading"><div><h3>Notification delivery & dead letters</h3><p>Provider acceptance, receipts, failure reasons, and safe retry.</p></div></div>{deliveries.map((delivery) => <article className="audit-row" key={delivery.id}><AlertTriangle /><div><strong>{delivery.notification_title}</strong><small>{delivery.channel} · {delivery.status} · {delivery.attempts} attempts</small>{delivery.error && <p>{delivery.error}</p>}</div>{['FAILED', 'DEAD'].includes(delivery.status) && <button className="secondary-button" onClick={async () => { await retryNotificationDelivery(session.token, delivery.id); await load(); notify('Delivery returned to retry queue') }}>Retry</button>}</article>)}</section></>
}
