import { FormEvent, useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { AlertTriangle, BellRing, Building2, CalendarDays, ClipboardCheck, Pencil, Plus, RefreshCw, ShieldCheck, Trash2, UserPlus, Users, X } from 'lucide-react'

import { PageHeader } from '../components/PageHeader'
import { useDialogFocus } from '../components/useDialogFocus'
import { adminDeactivateResource, adminSaveResource, getAdminOverview, retryNotificationDelivery } from '../lib/api'
import type { ApiUser, CareAssignment, CaregiverAvailability, EscalationPolicy, NotificationDelivery, Organization, Patient, Session, ShiftAssignment } from '../lib/types'

type Kind = 'user' | 'patient' | 'assignment' | 'shift' | 'availability' | 'policy' | 'escalation-step' | 'interaction' | 'task-template' | 'organization'
type Editor = { kind: Kind; id: number | null; values: Record<string, string | boolean> }
const paths: Record<Kind, string> = { user: 'users', patient: 'patients', assignment: 'assignments', shift: 'shift-assignments', availability: 'caregiver-availability', policy: 'escalation-policies', 'escalation-step': 'escalation-steps', interaction: 'medication-interactions', 'task-template': 'task-templates', organization: 'organizations' }

export default function AdminView({ session, notify, locale }: { session: Session; notify: (message: string) => void; locale: string }) {
  const fa = locale === 'fa'
  const t = (english: string, persian: string) => fa ? persian : english
  const statusLabel = (value: string) => ({ ADMIN: t('Administrator', 'مدیر'), CAREGIVER: t('Caregiver', 'مراقب'), DOCTOR: t('Doctor', 'پزشک'), FAMILY: t('Family', 'خانواده'), ACTIVE: t('Active', 'فعال'), INACTIVE: t('Inactive', 'غیرفعال'), SCHEDULED: t('Scheduled', 'برنامه‌ریزی‌شده'), COMPLETED: t('Completed', 'تکمیل‌شده'), CANCELED: t('Canceled', 'لغوشده'), AVAILABLE: t('Available', 'در دسترس'), UNAVAILABLE: t('Unavailable', 'در دسترس نیست'), DEFAULT: t('Default', 'پیش‌فرض'), CUSTOM: t('Custom', 'سفارشی'), PRIMARY_CAREGIVER: t('Primary caregiver', 'مراقب اصلی'), CLINICIAN: t('Clinician', 'پزشک'), FAMILY_MEMBER: t('Family member', 'عضو خانواده'), INFO: t('Information', 'اطلاعات'), WARNING: t('Warning', 'هشدار'), SEVERE: t('Severe', 'شدید'), LOW: t('Low', 'کم'), NORMAL: t('Normal', 'عادی'), HIGH: t('High', 'زیاد'), URGENT: t('Urgent', 'فوری'), PENDING: t('Pending', 'در انتظار'), SENT: t('Sent', 'ارسال‌شده'), FAILED: t('Failed', 'ناموفق'), DEAD: t('Stopped', 'متوقف‌شده'), SUPPRESSED: t('Suppressed', 'ارسال‌نشده'), PUSH: t('Push', 'اعلان'), SMS: t('SMS', 'پیامک'), VOICE: t('Voice call', 'تماس صوتی'), IN_APP: t('In-app', 'داخل برنامه'), PERSONAL_CARE: t('Personal care', 'مراقبت شخصی'), HEALTH: t('Health', 'سلامت'), MEAL: t('Meal', 'وعده غذایی'), ACTIVITY: t('Activity', 'فعالیت'), MEDICATION: t('Medication support', 'پشتیبانی دارو'), OTHER: t('Other', 'سایر') }[value] || value)
  const formatDate = (value: string) => new Intl.DateTimeFormat(fa ? 'fa-IR-u-ca-persian' : 'en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
  const formatDay = (value: string) => new Intl.DateTimeFormat(fa ? 'fa-IR-u-ca-persian' : 'en-GB', { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`))
  const [data, setData] = useState<{ users: ApiUser[]; patients: Patient[]; assignments: CareAssignment[]; shifts: ShiftAssignment[]; availability: CaregiverAvailability[]; policies: EscalationPolicy[]; organizations: Organization[]; deliveries: NotificationDelivery[]; steps: Record<string, unknown>[]; interactions: Record<string, unknown>[]; taskTemplates: Record<string, unknown>[] }>({ users: [], patients: [], assignments: [], shifts: [], availability: [], policies: [], organizations: [], deliveries: [], steps: [], interactions: [], taskTemplates: [] })
  const [editor, setEditor] = useState<Editor | null>(null)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  const [showAllDeliveries, setShowAllDeliveries] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await getAdminOverview(session.token)) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : (fa ? 'اطلاعات مدیریت بارگذاری نشد.' : 'Administration data could not be loaded.')) } finally { setLoading(false) } }, [session.token, fa])
  useEffect(() => { load() }, [load])
  const edit = (kind: Kind, item?: Record<string, unknown>) => {
    const values = Object.fromEntries(Object.entries(item || {}).filter(([key]) => !['id', 'created_at', 'updated_at'].includes(key)).map(([key, value]) => [key, value == null ? '' : value])) as Record<string, string | boolean>
    if (kind === 'task-template' && item?.schedule_defaults && typeof item.schedule_defaults === 'object') {
      const schedule = item.schedule_defaults as Record<string, unknown>
      values.frequency = String(schedule.frequency || 'DAILY'); values.time = String(schedule.time || '09:00').slice(0, 5)
    }
    setEditor({ kind, id: Number(item?.id) || null, values })
  }
  const save = async (next: Editor) => {
    const values: Record<string, unknown> = { ...next.values }
    for (const key of ['user', 'patient', 'caregiver', 'organization', 'level', 'delay_minutes']) if (values[key] !== undefined && values[key] !== '') values[key] = Number(values[key])
    if (next.kind === 'patient' && !next.id && !values.organization) values.organization = session.user.organization
    if (next.kind === 'user' && !next.id && !values.organization) values.organization = session.user.organization
    if (next.kind === 'policy' && !values.organization) values.organization = session.user.organization
    if (next.kind === 'interaction' && !values.organization) values.organization = session.user.organization
    if (next.kind === 'escalation-step') values.recipient_roles = String(values.recipient_roles || '').split(',').map((item) => item.trim().toUpperCase()).filter(Boolean)
    if (next.kind === 'task-template') {
      values.equipment = String(values.equipment || '').split(',').map((item) => item.trim()).filter(Boolean)
      values.schedule_defaults = { frequency: values.frequency || 'DAILY', time: values.time || '09:00' }
      delete values.frequency; delete values.time
    }
    await adminSaveResource(session.token, paths[next.kind], next.id, values); setEditor(null); await load(); notify(t(`${next.kind.replace('-', ' ')} saved`, 'تغییرات مدیریت ذخیره شد'))
  }
  const archive = async (kind: Kind, id: number) => { await adminDeactivateResource(session.token, paths[kind], id); await load(); notify(t(`${kind} deactivated`, 'مورد انتخاب‌شده غیرفعال شد')) }
  const activeUsers = data.users.filter((item) => item.is_active).length
  const unassignedPatients = data.patients.filter((patient) => !data.assignments.some((assignment) => assignment.active && assignment.patient === patient.id)).length
  const deliveryIssues = data.deliveries.filter((delivery) => ['FAILED', 'DEAD'].includes(delivery.status)).length
  const visibleDeliveries = showAllDeliveries ? data.deliveries : data.deliveries.slice(0, 8)
  return <><PageHeader eyebrow={t('ORGANIZATION OVERSIGHT', 'نظارت بر سازمان')} title={t('Administration', 'مدیریت')} description={t('Organizations, people, assignments, staffing, escalation chains, and notification delivery.', 'سازمان، افراد، واگذاری‌ها، شیفت‌ها، زنجیره‌های تشدید و تحویل اعلان‌ها.')} action={<div className="admin-header-actions"><button className="secondary-button" disabled={loading} onClick={load}><RefreshCw className={loading ? 'spinning' : ''} />{loading ? t('Refreshing', 'در حال به‌روزرسانی') : t('Refresh', 'به‌روزرسانی')}</button><button className="primary-button" onClick={() => edit('user')}><UserPlus />{t('Add team member', 'افزودن عضو تیم')}</button></div>} />
    {error && <div className="workspace-notice"><AlertTriangle />{error}<button onClick={load}>{t('Try again', 'تلاش دوباره')}</button></div>}
    <section className="admin-hero"><div><span className="eyebrow"><ShieldCheck />{t('CARE OPERATIONS', 'عملیات مراقبت')}</span><h2>{t('Run a safer, better connected care organization.', 'یک سازمان مراقبتی ایمن‌تر و هماهنگ‌تر اداره کنید.')}</h2><p>{t('Keep access, patient coverage, escalation policies, and delivery reliability visible from one workspace.', 'دسترسی، پوشش بیمار، سیاست‌های تشدید و قابلیت اطمینان ارسال را از یک فضای کاری بررسی کنید.')}</p><div className="admin-hero-actions"><button className="secondary-button" onClick={() => edit('patient')}><Plus />{t('Add patient', 'افزودن بیمار')}</button><button className="secondary-button" onClick={() => edit('assignment')}><ClipboardCheck />{t('Assign care', 'واگذاری مراقبت')}</button></div></div><div className={`admin-hero-status ${deliveryIssues ? 'attention' : ''}`}><BellRing /><span><small>{deliveryIssues ? t('Delivery attention needed', 'ارسال نیازمند بررسی است') : t('Delivery operations healthy', 'عملیات ارسال سالم است')}</small><strong>{deliveryIssues ? fa ? `${deliveryIssues} مورد نیازمند بررسی است` : `${deliveryIssues} item${deliveryIssues === 1 ? '' : 's'} need review` : t('No failed deliveries', 'ارسال ناموفقی وجود ندارد')}</strong></span></div></section>
    <section className="admin-metric-grid" aria-label={t('Administration overview', 'نمای کلی مدیریت')}><AdminMetric icon={<Users />} value={activeUsers} label={t('Active team members', 'اعضای فعال تیم')} /><AdminMetric icon={<Users />} value={data.patients.filter((item) => item.active).length} label={t('Active patients', 'بیماران فعال')} /><AdminMetric icon={<ClipboardCheck />} value={unassignedPatients} label={t('Patients without coverage', 'بیماران بدون پوشش')} attention={unassignedPatients > 0} /><AdminMetric icon={<BellRing />} value={deliveryIssues} label={t('Delivery issues', 'مشکلات ارسال')} attention={deliveryIssues > 0} /></section>
    <div className="admin-grid">
      <AdminSection title={t('Staff & permissions', 'کارکنان و دسترسی‌ها')} detail={t('Roles, account access, and deactivation.', 'نقش‌ها، دسترسی حساب و غیرفعال‌سازی.')} count={data.users.length} icon={<Users />} onAdd={() => edit('user')} empty={t('Add the first team member to begin assigning care.', 'برای شروع واگذاری مراقبت، نخستین عضو تیم را اضافه کنید.')} addLabel={t('Add', 'افزودن')}>{data.users.map((item) => <Row key={item.id} title={item.display_name} detail={`${statusLabel(item.role)} · ${item.email}`} state={item.is_active ? t('Active', 'فعال') : t('Disabled', 'غیرفعال')} tone={item.is_active ? 'positive' : 'neutral'} editLabel={t('Edit', 'ویرایش')} deactivateLabel={t('Deactivate', 'غیرفعال‌سازی')} onEdit={() => edit('user', item)} onArchive={item.is_active ? () => archive('user', item.id) : undefined} />)}</AdminSection>
      <AdminSection title={t('Patients', 'بیماران')} detail={t('Care recipients and room information.', 'دریافت‌کنندگان مراقبت و اطلاعات اتاق.')} count={data.patients.length} icon={<Users />} onAdd={() => edit('patient')} empty={t('Add a patient before creating care assignments.', 'پیش از ایجاد واگذاری مراقبت، یک بیمار اضافه کنید.')} addLabel={t('Add', 'افزودن')}>{data.patients.map((item) => <Row key={item.id} title={item.full_name} detail={`${formatDay(item.birth_date)} · ${item.room || t('No room recorded', 'اتاق ثبت نشده')}`} state={item.active ? t('Active', 'فعال') : t('Disabled', 'غیرفعال')} tone={item.active ? 'positive' : 'neutral'} editLabel={t('Edit', 'ویرایش')} deactivateLabel={t('Deactivate', 'غیرفعال‌سازی')} onEdit={() => edit('patient', item)} onArchive={item.active ? () => archive('patient', item.id) : undefined} />)}</AdminSection>
      <AdminSection title={t('Care assignments', 'واگذاری‌های مراقبت')} detail={t('Who can view and record care for each patient.', 'افرادی که می‌توانند مراقبت هر بیمار را ببینند و ثبت کنند.')} count={data.assignments.length} icon={<ClipboardCheck />} onAdd={() => edit('assignment')} empty={t('Assign a caregiver, clinician, or family member to a patient.', 'یک مراقب، پزشک یا عضو خانواده را به بیمار واگذار کنید.')} addLabel={t('Add', 'افزودن')}>{data.assignments.map((item) => <Row key={item.id} title={`${item.user_detail.display_name} → ${item.patient_name}`} detail={statusLabel(item.relationship)} state={item.active ? t('Active', 'فعال') : t('Inactive', 'غیرفعال')} tone={item.active ? 'positive' : 'neutral'} editLabel={t('Edit', 'ویرایش')} deactivateLabel={t('Deactivate', 'غیرفعال‌سازی')} onEdit={() => edit('assignment', item)} onArchive={item.active ? () => archive('assignment', item.id) : undefined} />)}</AdminSection>
      <AdminSection title={t('Shifts', 'شیفت‌ها')} detail={t('Scheduled caregiver coverage and handover windows.', 'پوشش زمان‌بندی‌شده مراقب و بازه‌های تحویل شیفت.')} count={data.shifts.length} icon={<CalendarDays />} onAdd={() => edit('shift')} empty={t('Create a shift to show coverage on the calendar.', 'برای نمایش پوشش در تقویم، یک شیفت ایجاد کنید.')} addLabel={t('Add', 'افزودن')}>{data.shifts.map((item) => <Row key={item.id} title={item.caregiver_name} detail={`${formatDate(item.starts_at)} – ${formatDate(item.ends_at)}`} state={statusLabel(item.status)} tone={item.status === 'CANCELED' ? 'danger' : 'positive'} editLabel={t('Edit', 'ویرایش')} deactivateLabel={t('Deactivate', 'لغو')} onEdit={() => edit('shift', item)} onArchive={!['COMPLETED', 'CANCELED'].includes(item.status) ? () => archive('shift', item.id) : undefined} />)}</AdminSection>
      <AdminSection title={t('Caregiver availability', 'دسترس‌پذیری مراقب')} detail={t('Availability and leave periods used for coverage review.', 'دسترس‌پذیری و مرخصی برای بررسی پوشش.')} count={data.availability.length} icon={<CalendarDays />} onAdd={() => edit('availability')} empty={t('Record availability or leave to make staffing risks visible.', 'دسترس‌پذیری یا مرخصی را ثبت کنید تا ریسک‌های نیرو قابل مشاهده باشند.')} addLabel={t('Add', 'افزودن')}>{data.availability.map((item) => <Row key={item.id} title={item.caregiver_name} detail={`${formatDate(item.starts_at)} – ${formatDate(item.ends_at)}`} state={item.available ? t('Available', 'در دسترس') : t('Unavailable', 'در دسترس نیست')} tone={item.available ? 'positive' : 'danger'} editLabel={t('Edit', 'ویرایش')} onEdit={() => edit('availability', item)} />)}</AdminSection>
      <AdminSection title={t('Escalation policies', 'سیاست‌های تشدید')} detail={t('Ownership and timing rules for critical care alerts.', 'مالکیت و قوانین زمان‌بندی هشدارهای ضروری مراقبت.')} count={data.policies.length} icon={<BellRing />} onAdd={() => edit('policy')} empty={t('Create an escalation policy before adding its steps.', 'پیش از افزودن مرحله‌ها، یک سیاست تشدید ایجاد کنید.')} addLabel={t('Add', 'افزودن')}>{data.policies.map((item) => <Row key={item.id} title={item.name} detail={item.steps.map((step) => `L${step.level} ${statusLabel(step.channel)} +${step.delay_minutes}${fa ? 'دقیقه' : 'm'}`).join(' · ') || t('No escalation steps', 'بدون مرحله تشدید')} state={item.is_default ? t('Default', 'پیش‌فرض') : t('Custom', 'سفارشی')} tone={item.is_default ? 'positive' : 'neutral'} editLabel={t('Edit', 'ویرایش')} onEdit={() => edit('policy', item)} />)}<button className="admin-inline-action" onClick={() => edit('escalation-step')}><Plus />{t('Add escalation step', 'افزودن مرحله تشدید')}</button></AdminSection>
      <AdminSection title={t('Medication interaction catalog', 'فهرست تداخلات دارویی')} detail={t('Organization safety warnings for duplicate or interacting medicines.', 'هشدارهای ایمنی سازمان برای داروهای تکراری یا دارای تداخل.')} count={data.interactions.length} icon={<AlertTriangle />} onAdd={() => edit('interaction')} empty={t('Add reviewed interaction guidance for the care team.', 'راهنمای تأییدشده تداخل دارویی را برای تیم مراقبت اضافه کنید.')} addLabel={t('Add', 'افزودن')}>{data.interactions.map((item) => <Row key={Number(item.id)} title={`${String(item.medication_a)} + ${String(item.medication_b)}`} detail={String(item.message)} state={statusLabel(String(item.severity))} tone={String(item.severity) === 'SEVERE' ? 'danger' : 'neutral'} editLabel={t('Edit', 'ویرایش')} onEdit={() => edit('interaction', item)} />)}</AdminSection>
      <AdminSection title={t('Care task templates', 'الگوهای وظیفه مراقبتی')} detail={t('Reusable, safer starting points for recurring care.', 'نقطه شروع‌های ایمن و قابل استفاده مجدد برای مراقبت تکرارشونده.')} count={data.taskTemplates.length} icon={<ClipboardCheck />} onAdd={() => edit('task-template')} empty={t('Create a template to standardize frequent care tasks.', 'برای استانداردسازی وظایف پرتکرار، یک الگو ایجاد کنید.')} addLabel={t('Add', 'افزودن')}>{data.taskTemplates.map((item) => <Row key={Number(item.id)} title={String(item.name)} detail={statusLabel(String(item.category))} state={statusLabel(String(item.priority))} tone={String(item.priority) === 'URGENT' ? 'danger' : 'neutral'} editLabel={t('Edit', 'ویرایش')} onEdit={() => edit('task-template', item)} />)}</AdminSection>
      <AdminSection title={t('Organization settings', 'تنظیمات سازمان')} detail={t('Identity, geography, and local time zone.', 'هویت، موقعیت جغرافیایی و منطقه زمانی محلی.')} count={data.organizations.length} icon={<Building2 />} empty={t('No organization is available for this administrator.', 'هیچ سازمانی برای این مدیر در دسترس نیست.')} addLabel={t('Add', 'افزودن')}>{data.organizations.map((item) => <Row key={item.id} title={item.name} detail={`${item.timezone} · ${item.country_code || t('No country recorded', 'کشور ثبت نشده')}`} state={item.active ? t('Active', 'فعال') : t('Inactive', 'غیرفعال')} tone={item.active ? 'positive' : 'neutral'} editLabel={t('Edit', 'ویرایش')} onEdit={() => edit('organization', item)} />)}</AdminSection>
    </div>
    <section className="main-card admin-delivery-panel"><div className="admin-section-heading"><span><BellRing /></span><div><h2>{t('Notification delivery & dead letters', 'تحویل اعلان‌ها و پیام‌های متوقف‌شده')}</h2><p>{t('Provider receipts, failure reasons, and safe retry.', 'رسید ارائه‌دهنده، دلیل خطا و تلاش مجدد ایمن.')}</p></div><b>{data.deliveries.length}</b></div>{data.deliveries.length ? <>{visibleDeliveries.map((delivery) => <article className={`admin-delivery-row ${['FAILED', 'DEAD'].includes(delivery.status) ? 'failed' : ''}`} key={delivery.id}><AlertTriangle /><div><strong>{delivery.notification_title}</strong><small>{statusLabel(delivery.channel)} · {statusLabel(delivery.status)} · {fa ? `${delivery.attempts} تلاش` : `${delivery.attempts} attempts`}</small>{delivery.error && <p>{delivery.error}</p>}</div>{['FAILED', 'DEAD'].includes(delivery.status) && <button className="secondary-button" onClick={async () => { await retryNotificationDelivery(session.token, delivery.id); await load(); notify(t('Delivery returned to retry queue', 'ارسال دوباره در صف تلاش قرار گرفت')) }}>{t('Retry delivery', 'تلاش مجدد برای ارسال')}</button>}</article>)}{data.deliveries.length > 8 && <button className="admin-show-all" onClick={() => setShowAllDeliveries((current) => !current)}>{showAllDeliveries ? t('Show recent deliveries', 'نمایش ارسال‌های اخیر') : fa ? `نمایش همه ${data.deliveries.length} ارسال` : `Show all ${data.deliveries.length} deliveries`}</button>}</> : <AdminEmpty detail={t('No notification deliveries have been recorded yet.', 'هنوز هیچ تحویل اعلانی ثبت نشده است.')} />}</section>
    {editor && <AdminEditor editor={editor} users={data.users} patients={data.patients} policies={data.policies} fa={fa} onClose={() => setEditor(null)} onSave={save} />}</>
}

function AdminMetric({ icon, value, label, attention = false }: { icon: ReactNode; value: number; label: string; attention?: boolean }) { return <article className={attention ? 'attention' : ''}><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></article> }
function AdminEmpty({ detail }: { detail: string }) { return <div className="admin-empty"><ClipboardCheck /><p>{detail}</p></div> }
function AdminSection({ title, detail, count, icon, onAdd, empty, addLabel, children }: { title: string; detail: string; count: number; icon: ReactNode; onAdd?: () => void; empty: string; addLabel: string; children: ReactNode }) { return <section className="main-card admin-section"><header className="admin-section-heading"><span>{icon}</span><div><h2>{title}</h2><p>{detail}</p></div><b>{count}</b>{onAdd && <button className="admin-add-button" onClick={onAdd}><Plus /><span>{addLabel}</span></button>}</header><div className="admin-section-list">{count ? children : <AdminEmpty detail={empty} />}</div></section> }
function Row({ title, detail, state, tone = 'neutral', editLabel, deactivateLabel, onEdit, onArchive }: { title: string; detail: string; state: string; tone?: 'positive' | 'neutral' | 'danger'; editLabel: string; deactivateLabel?: string; onEdit: () => void; onArchive?: () => void }) { return <article className="admin-row"><div className="admin-row-copy"><strong>{title}<b className={`admin-state ${tone}`}>{state}</b></strong><small>{detail}</small></div><div className="admin-row-actions"><button className="text-button" onClick={onEdit}><Pencil />{editLabel}</button>{onArchive && <button className="text-button danger-text" onClick={onArchive}><Trash2 />{deactivateLabel}</button>}</div></article> }

function AdminEditor({ editor, users, patients, policies, fa, onClose, onSave }: { editor: Editor; users: ApiUser[]; patients: Patient[]; policies: EscalationPolicy[]; fa: boolean; onClose: () => void; onSave: (editor: Editor) => Promise<void> }) {
  const t = (english: string, persian: string) => fa ? persian : english
  const kindLabel = ({ user: t('team member', 'عضو تیم'), patient: t('patient', 'بیمار'), assignment: t('care assignment', 'واگذاری مراقبت'), shift: t('shift', 'شیفت'), availability: t('availability', 'دسترس‌پذیری'), policy: t('escalation policy', 'سیاست تشدید'), 'escalation-step': t('escalation step', 'مرحله تشدید'), interaction: t('medication interaction', 'تداخل دارویی'), 'task-template': t('care task template', 'الگوی وظیفه مراقبتی'), organization: t('organization', 'سازمان') })[editor.kind]
  const [values, setValues] = useState(editor.values)
  const [error, setError] = useState('')
  const dialogRef = useRef<HTMLFormElement>(null)
  useDialogFocus(dialogRef, onClose)
  const set = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }))
  const common = (key: string, label: string, type = 'text', required = true) => <label key={key}>{label}<input type={type} required={required} value={String(values[key] ?? '')} onChange={(event) => set(key, event.target.value)} /></label>
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await onSave({ ...editor, values }) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : t('Record could not be saved.', 'ذخیره این مورد انجام نشد.')) } }
  return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose} aria-label={t('Close administration editor', 'بستن ویرایشگر مدیریت')} tabIndex={-1} /><form ref={dialogRef} className="modal task-form admin-editor" role="dialog" aria-modal="true" aria-label={`${editor.id ? t('Edit', 'ویرایش') : t('Add', 'افزودن')} ${kindLabel}`} tabIndex={-1} onSubmit={submit}><button type="button" className="modal-close" onClick={onClose} aria-label={t('Close administration editor', 'بستن ویرایشگر مدیریت')}><X /></button><span className="eyebrow">{t('ADMINISTRATION', 'مدیریت')}</span><h2>{editor.id ? t('Edit', 'ویرایش') : t('Add', 'افزودن')} {kindLabel}</h2><p className="admin-editor-description">{t('Review each value carefully before saving changes to the care workspace.', 'پیش از ذخیره تغییرات در فضای کاری مراقبت، هر مقدار را با دقت بررسی کنید.')}</p>
    {editor.kind === 'user' && <>{common('username', t('Username', 'نام کاربری'))}{common('email', t('Email', 'ایمیل'), 'email')}{common('first_name', t('First name', 'نام'))}{common('last_name', t('Last name', 'نام خانوادگی'))}{!editor.id && common('password', t('Temporary password', 'گذرواژه موقت'), 'password')}<label>{t('Role', 'نقش')}<select value={String(values.role || 'CAREGIVER')} onChange={(event) => set('role', event.target.value)}><option value="CAREGIVER">{t('Caregiver', 'مراقب')}</option><option value="DOCTOR">{t('Doctor', 'پزشک')}</option><option value="FAMILY">{t('Family', 'خانواده')}</option><option value="ADMIN">{t('Administrator', 'مدیر')}</option></select></label></>}
    {editor.kind === 'patient' && <>{common('first_name', t('First name', 'نام'))}{common('last_name', t('Last name', 'نام خانوادگی'))}{common('birth_date', t('Birth date', 'تاریخ تولد'), 'date')}<label>{t('Gender', 'جنسیت')}<select value={String(values.gender || 'UNDISCLOSED')} onChange={(event) => set('gender', event.target.value)}><option value="UNDISCLOSED">{t('Undisclosed', 'اعلام‌نشده')}</option><option value="FEMALE">{t('Female', 'زن')}</option><option value="MALE">{t('Male', 'مرد')}</option><option value="OTHER">{t('Other', 'سایر')}</option></select></label>{common('room', t('Room', 'اتاق'), 'text', false)}</>}
    {editor.kind === 'assignment' && <><label>{t('User', 'کاربر')}<select required value={String(values.user || '')} onChange={(event) => set('user', event.target.value)}><option value="">{t('Select user', 'کاربر را انتخاب کنید')}</option>{users.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label>{t('Patient', 'بیمار')}<select required value={String(values.patient || '')} onChange={(event) => set('patient', event.target.value)}><option value="">{t('Select patient', 'بیمار را انتخاب کنید')}</option>{patients.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label>{common('relationship', t('Relationship', 'نوع ارتباط'))}</>}
    {editor.kind === 'shift' && <><label>{t('Caregiver', 'مراقب')}<select required value={String(values.caregiver || '')} onChange={(event) => set('caregiver', event.target.value)}><option value="">{t('Select caregiver', 'مراقب را انتخاب کنید')}</option>{users.filter((item) => item.role === 'CAREGIVER').map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label>{t('Patient', 'بیمار')}<select required value={String(values.patient || '')} onChange={(event) => set('patient', event.target.value)}><option value="">{t('Select patient', 'بیمار را انتخاب کنید')}</option>{patients.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label>{common('starts_at', t('Starts', 'شروع'), 'datetime-local')}{common('ends_at', t('Ends', 'پایان'), 'datetime-local')}{common('notes', t('Notes', 'یادداشت'), 'text', false)}</>}
    {editor.kind === 'availability' && <><label>{t('Caregiver', 'مراقب')}<select required value={String(values.caregiver || '')} onChange={(event) => set('caregiver', event.target.value)}>{users.filter((item) => item.role === 'CAREGIVER').map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label>{common('starts_at', t('Starts', 'شروع'), 'datetime-local')}{common('ends_at', t('Ends', 'پایان'), 'datetime-local')}{common('note', t('Note', 'یادداشت'), 'text', false)}<label className="checkbox"><input type="checkbox" checked={values.available !== false} onChange={(event) => set('available', event.target.checked)} /><span>{t('Available', 'در دسترس')}</span></label></>}
    {editor.kind === 'policy' && <>{common('name', t('Policy name', 'نام سیاست'))}<label className="checkbox"><input type="checkbox" checked={values.is_default === true} onChange={(event) => set('is_default', event.target.checked)} /><span>{t('Default policy', 'سیاست پیش‌فرض')}</span></label></>}
    {editor.kind === 'escalation-step' && <><label>{t('Policy', 'سیاست')}<select required value={String(values.policy || '')} onChange={(event) => set('policy', event.target.value)}><option value="">{t('Select policy', 'سیاست را انتخاب کنید')}</option>{policies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{common('level', t('Escalation level', 'سطح تشدید'), 'number')}{common('delay_minutes', t('Delay in minutes', 'تاخیر به دقیقه'), 'number')}<label>{t('Channel', 'کانال')}<select value={String(values.channel || 'IN_APP')} onChange={(event) => set('channel', event.target.value)}><option value="IN_APP">{t('In app', 'داخل برنامه')}</option><option value="PUSH">{t('Push', 'اعلان')}</option><option value="SMS">{t('SMS', 'پیامک')}</option><option value="VOICE">{t('Voice call', 'تماس صوتی')}</option></select></label>{common('recipient_roles', t('Recipient roles (comma-separated)', 'نقش‌های دریافت‌کننده (با ویرگول جدا کنید)'), 'text', false)}</>}
    {editor.kind === 'interaction' && <>{common('medication_a', t('Medication A', 'داروی اول'))}{common('medication_b', t('Medication B', 'داروی دوم'))}<label>{t('Severity', 'شدت')}<select value={String(values.severity || 'WARNING')} onChange={(event) => set('severity', event.target.value)}><option value="INFO">{t('Information', 'اطلاعات')}</option><option value="WARNING">{t('Warning', 'هشدار')}</option><option value="SEVERE">{t('Severe', 'شدید')}</option></select></label>{common('message', t('Warning message', 'متن هشدار'))}{common('source', t('Evidence source', 'منبع شواهد'))}</>}
    {editor.kind === 'task-template' && <>{common('name', t('Template name', 'نام الگو'))}{common('title', t('Task title', 'عنوان وظیفه'))}<label>{t('Category', 'دسته‌بندی')}<select value={String(values.category || 'PERSONAL_CARE')} onChange={(event) => set('category', event.target.value)}><option value="PERSONAL_CARE">{t('Personal care', 'مراقبت شخصی')}</option><option value="HEALTH">{t('Health', 'سلامت')}</option><option value="MEAL">{t('Meal', 'وعده غذایی')}</option><option value="ACTIVITY">{t('Activity', 'فعالیت')}</option><option value="MEDICATION">{t('Medication support', 'پشتیبانی دارو')}</option><option value="OTHER">{t('Other', 'سایر')}</option></select></label><label>{t('Priority', 'اولویت')}<select value={String(values.priority || 'NORMAL')} onChange={(event) => set('priority', event.target.value)}><option value="LOW">{t('Low', 'کم')}</option><option value="NORMAL">{t('Normal', 'عادی')}</option><option value="HIGH">{t('High', 'زیاد')}</option><option value="URGENT">{t('Urgent', 'فوری')}</option></select></label>{common('instructions', t('Care instructions', 'دستور مراقبت'))}{common('expected_outcome', t('Expected outcome', 'نتیجه مورد انتظار'), 'text', false)}{common('safety_notes', t('Safety notes', 'یادداشت‌های ایمنی'), 'text', false)}{common('equipment', t('Equipment (comma-separated)', 'تجهیزات (با ویرگول جدا کنید)'), 'text', false)}<div className="form-row"><label>{t('Frequency', 'تناوب')}<select value={String(values.frequency || 'DAILY')} onChange={(event) => set('frequency', event.target.value)}><option value="DAILY">{t('Daily', 'روزانه')}</option><option value="WEEKLY">{t('Weekly', 'هفتگی')}</option><option value="ONCE">{t('One time', 'یک‌بار')}</option><option value="INTERVAL">{t('Interval', 'بازه‌ای')}</option></select></label>{common('time', t('Default time', 'زمان پیش‌فرض'), 'time')}</div></>}
    {editor.kind === 'organization' && <>{common('name', t('Organization name', 'نام سازمان'))}{common('slug', t('Slug', 'نامک'))}{common('country_code', t('Country code', 'کد کشور'), 'text', false)}{common('timezone', t('IANA timezone', 'منطقه زمانی IANA'))}</>}
    {error && <div className="login-error" role="alert"><AlertTriangle />{error}</div>}<div className="admin-editor-actions"><button type="button" className="secondary-button" onClick={onClose}>{t('Cancel', 'انصراف')}</button><button className="primary-button">{t('Save changes', 'ذخیره تغییرات')}</button></div></form></div>
}
