import { FormEvent, useCallback, useEffect, useState, type ReactNode } from 'react'
import { AlertTriangle, BellRing, Building2, CalendarDays, Pencil, Plus, RefreshCw, Trash2, Users, X } from 'lucide-react'

import { PageHeader } from '../components/PageHeader'
import { adminDeactivateResource, adminSaveResource, getAdminOverview, retryNotificationDelivery } from '../lib/api'
import type { ApiUser, CareAssignment, CaregiverAvailability, EscalationPolicy, NotificationDelivery, Organization, Patient, Session, ShiftAssignment } from '../lib/types'

type Kind = 'user' | 'patient' | 'assignment' | 'shift' | 'availability' | 'policy' | 'escalation-step' | 'interaction' | 'task-template' | 'organization'
type Editor = { kind: Kind; id: number | null; values: Record<string, string | boolean> }
const paths: Record<Kind, string> = { user: 'users', patient: 'patients', assignment: 'assignments', shift: 'shift-assignments', availability: 'caregiver-availability', policy: 'escalation-policies', 'escalation-step': 'escalation-steps', interaction: 'medication-interactions', 'task-template': 'task-templates', organization: 'organizations' }

export default function AdminView({ session, notify }: { session: Session; notify: (message: string) => void }) {
  const [data, setData] = useState<{ users: ApiUser[]; patients: Patient[]; assignments: CareAssignment[]; shifts: ShiftAssignment[]; availability: CaregiverAvailability[]; policies: EscalationPolicy[]; organizations: Organization[]; deliveries: NotificationDelivery[]; steps: Record<string, unknown>[]; interactions: Record<string, unknown>[]; taskTemplates: Record<string, unknown>[] }>({ users: [], patients: [], assignments: [], shifts: [], availability: [], policies: [], organizations: [], deliveries: [], steps: [], interactions: [], taskTemplates: [] })
  const [editor, setEditor] = useState<Editor | null>(null)
  const [error, setError] = useState('')
  const load = useCallback(async () => { setError(''); try { setData(await getAdminOverview(session.token)) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Administration data could not be loaded.') } }, [session.token])
  useEffect(() => { load() }, [load])
  const edit = (kind: Kind, item?: Record<string, unknown>) => {
    const values = Object.fromEntries(Object.entries(item || {}).filter(([key]) => !['id', 'created_at', 'updated_at'].includes(key)).map(([key, value]) => [key, value == null ? '' : value])) as Record<string, string | boolean>
    if (kind === 'task-template' && item?.schedule_defaults && typeof item.schedule_defaults === 'object') {
      const schedule = item.schedule_defaults as Record<string, unknown>
      values.frequency = String(schedule.frequency || 'DAILY'); values.time = String(schedule.time || '09:00').slice(0, 5)
    }
    setEditor({ kind, id: Number(item?.id) || null, values })
  }
  const save = async (next: Editor) => {
    const values: Record<string, unknown> = { ...next.values }
    for (const key of ['user', 'patient', 'caregiver', 'organization', 'level', 'delay_minutes']) if (values[key] !== undefined && values[key] !== '') values[key] = Number(values[key])
    if (next.kind === 'patient' && !next.id && !values.organization) values.organization = session.user.organization
    if (next.kind === 'user' && !next.id && !values.organization) values.organization = session.user.organization
    if (next.kind === 'policy' && !values.organization) values.organization = session.user.organization
    if (next.kind === 'interaction' && !values.organization) values.organization = session.user.organization
    if (next.kind === 'escalation-step') values.recipient_roles = String(values.recipient_roles || '').split(',').map((item) => item.trim().toUpperCase()).filter(Boolean)
    if (next.kind === 'task-template') {
      values.equipment = String(values.equipment || '').split(',').map((item) => item.trim()).filter(Boolean)
      values.schedule_defaults = { frequency: values.frequency || 'DAILY', time: values.time || '09:00' }
      delete values.frequency; delete values.time
    }
    await adminSaveResource(session.token, paths[next.kind], next.id, values); setEditor(null); await load(); notify(`${next.kind.replace('-', ' ')} saved`)
  }
  const archive = async (kind: Kind, id: number) => { await adminDeactivateResource(session.token, paths[kind], id); await load(); notify(`${kind} deactivated`) }
  return <><PageHeader eyebrow="ORGANIZATION OVERSIGHT" title="Administration" description="Organizations, people, assignments, staffing, escalation chains, and notification delivery." action={<button className="secondary-button" onClick={load}><RefreshCw />Refresh</button>} />
    {error && <div className="workspace-notice"><AlertTriangle />{error}<button onClick={load}>Try again</button></div>}
    <div className="admin-grid">
      <AdminSection title="Staff & permissions" icon={<Users />} onAdd={() => edit('user')}>{data.users.map((item) => <Row key={item.id} title={item.display_name} detail={`${item.role} · ${item.email} · ${item.is_active ? 'Active' : 'Disabled'}`} onEdit={() => edit('user', item)} onArchive={item.is_active ? () => archive('user', item.id) : undefined} />)}</AdminSection>
      <AdminSection title="Patients" icon={<Users />} onAdd={() => edit('patient')}>{data.patients.map((item) => <Row key={item.id} title={item.full_name} detail={`${item.birth_date} · ${item.room || 'No room'} · ${item.active ? 'Active' : 'Disabled'}`} onEdit={() => edit('patient', item)} onArchive={item.active ? () => archive('patient', item.id) : undefined} />)}</AdminSection>
      <AdminSection title="Care assignments" icon={<Users />} onAdd={() => edit('assignment')}>{data.assignments.map((item) => <Row key={item.id} title={`${item.user_detail.display_name} → ${item.patient_name}`} detail={`${item.relationship} · ${item.active ? 'Active' : 'Inactive'}`} onEdit={() => edit('assignment', item)} onArchive={item.active ? () => archive('assignment', item.id) : undefined} />)}</AdminSection>
      <AdminSection title="Shifts" icon={<CalendarDays />} onAdd={() => edit('shift')}>{data.shifts.map((item) => <Row key={item.id} title={`${item.caregiver_name} · ${item.status}`} detail={`${new Date(item.starts_at).toLocaleString()} – ${new Date(item.ends_at).toLocaleString()}`} onEdit={() => edit('shift', item)} onArchive={!['COMPLETED', 'CANCELED'].includes(item.status) ? () => archive('shift', item.id) : undefined} />)}</AdminSection>
      <AdminSection title="Caregiver availability" icon={<CalendarDays />} onAdd={() => edit('availability')}>{data.availability.map((item) => <Row key={item.id} title={item.caregiver_name} detail={`${item.available ? 'Available' : 'Unavailable'} · ${new Date(item.starts_at).toLocaleString()} – ${new Date(item.ends_at).toLocaleString()}`} onEdit={() => edit('availability', item)} />)}</AdminSection>
      <AdminSection title="Escalation policies" icon={<BellRing />} onAdd={() => edit('policy')}>{data.policies.map((item) => <Row key={item.id} title={`${item.name}${item.is_default ? ' · Default' : ''}`} detail={item.steps.map((step) => `L${step.level} ${step.channel} +${step.delay_minutes}m`).join(' · ') || 'No escalation steps'} onEdit={() => edit('policy', item)} />)}<button className="secondary-button" onClick={() => edit('escalation-step')}><Plus />Add escalation step</button></AdminSection>
      <AdminSection title="Medication interaction catalog" icon={<AlertTriangle />} onAdd={() => edit('interaction')}>{data.interactions.map((item) => <Row key={Number(item.id)} title={`${String(item.medication_a)} + ${String(item.medication_b)}`} detail={`${String(item.severity)} · ${String(item.message)}`} onEdit={() => edit('interaction', item)} />)}</AdminSection>
      <AdminSection title="Care task templates" icon={<CalendarDays />} onAdd={() => edit('task-template')}>{data.taskTemplates.map((item) => <Row key={Number(item.id)} title={String(item.name)} detail={`${String(item.category)} · ${String(item.priority)}`} onEdit={() => edit('task-template', item)} />)}</AdminSection>
      <AdminSection title="Organization settings" icon={<Building2 />}>{data.organizations.map((item) => <Row key={item.id} title={item.name} detail={`${item.timezone} · ${item.country_code || 'No country'} · ${item.active ? 'Active' : 'Inactive'}`} onEdit={() => edit('organization', item)} />)}</AdminSection>
    </div>
    <section className="main-card recent-readings"><div className="subsection-heading"><div><h3>Notification delivery & dead letters</h3><p>Provider receipts, failure reasons, and safe retry.</p></div></div>{data.deliveries.map((delivery) => <article className="audit-row" key={delivery.id}><AlertTriangle /><div><strong>{delivery.notification_title}</strong><small>{delivery.channel} · {delivery.status} · {delivery.attempts} attempts</small>{delivery.error && <p>{delivery.error}</p>}</div>{['FAILED', 'DEAD'].includes(delivery.status) && <button className="secondary-button" onClick={async () => { await retryNotificationDelivery(session.token, delivery.id); await load(); notify('Delivery returned to retry queue') }}>Retry</button>}</article>)}</section>
    {editor && <AdminEditor editor={editor} users={data.users} patients={data.patients} policies={data.policies} onClose={() => setEditor(null)} onSave={save} />}</>
}

function AdminSection({ title, icon, onAdd, children }: { title: string; icon: ReactNode; onAdd?: () => void; children: ReactNode }) { return <section className="main-card clinical-section"><h3>{icon}{title}{onAdd && <button className="text-button" onClick={onAdd}><Plus />Add</button>}</h3>{children}</section> }
function Row({ title, detail, onEdit, onArchive }: { title: string; detail: string; onEdit: () => void; onArchive?: () => void }) { return <article><span><strong>{title}</strong><small>{detail}</small></span><div className="med-actions"><button className="text-button" onClick={onEdit}><Pencil />Edit</button>{onArchive && <button className="text-button danger-text" onClick={onArchive}><Trash2 />Deactivate</button>}</div></article> }

function AdminEditor({ editor, users, patients, policies, onClose, onSave }: { editor: Editor; users: ApiUser[]; patients: Patient[]; policies: EscalationPolicy[]; onClose: () => void; onSave: (editor: Editor) => Promise<void> }) {
  const [values, setValues] = useState(editor.values)
  const [error, setError] = useState('')
  const set = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }))
  const common = (key: string, label: string, type = 'text', required = true) => <label key={key}>{label}<input type={type} required={required} value={String(values[key] ?? '')} onChange={(event) => set(key, event.target.value)} /></label>
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await onSave({ ...editor, values }) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Record could not be saved.') } }
  return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose} aria-label="Close administration editor" /><form className="modal task-form" role="dialog" aria-modal="true" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}><X /></button><h2>{editor.id ? 'Edit' : 'Add'} {editor.kind}</h2>
    {editor.kind === 'user' && <>{common('username', 'Username')}{common('email', 'Email', 'email')}{common('first_name', 'First name')}{common('last_name', 'Last name')}{!editor.id && common('password', 'Temporary password', 'password')}<label>Role<select value={String(values.role || 'CAREGIVER')} onChange={(event) => set('role', event.target.value)}><option value="CAREGIVER">Caregiver</option><option value="DOCTOR">Doctor</option><option value="FAMILY">Family</option><option value="ADMIN">Administrator</option></select></label></>}
    {editor.kind === 'patient' && <>{common('first_name', 'First name')}{common('last_name', 'Last name')}{common('birth_date', 'Birth date', 'date')}<label>Gender<select value={String(values.gender || 'UNDISCLOSED')} onChange={(event) => set('gender', event.target.value)}><option value="UNDISCLOSED">Undisclosed</option><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="OTHER">Other</option></select></label>{common('room', 'Room', 'text', false)}</>}
    {editor.kind === 'assignment' && <><label>User<select required value={String(values.user || '')} onChange={(event) => set('user', event.target.value)}><option value="">Select user</option>{users.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label>Patient<select required value={String(values.patient || '')} onChange={(event) => set('patient', event.target.value)}><option value="">Select patient</option>{patients.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label>{common('relationship', 'Relationship')}</>}
    {editor.kind === 'shift' && <><label>Caregiver<select required value={String(values.caregiver || '')} onChange={(event) => set('caregiver', event.target.value)}><option value="">Select caregiver</option>{users.filter((item) => item.role === 'CAREGIVER').map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label>Patient<select required value={String(values.patient || '')} onChange={(event) => set('patient', event.target.value)}><option value="">Select patient</option>{patients.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label>{common('starts_at', 'Starts', 'datetime-local')}{common('ends_at', 'Ends', 'datetime-local')}{common('notes', 'Notes', 'text', false)}</>}
    {editor.kind === 'availability' && <><label>Caregiver<select required value={String(values.caregiver || '')} onChange={(event) => set('caregiver', event.target.value)}>{users.filter((item) => item.role === 'CAREGIVER').map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label>{common('starts_at', 'Starts', 'datetime-local')}{common('ends_at', 'Ends', 'datetime-local')}{common('note', 'Note', 'text', false)}<label className="checkbox"><input type="checkbox" checked={values.available !== false} onChange={(event) => set('available', event.target.checked)} /><span>Available</span></label></>}
    {editor.kind === 'policy' && <>{common('name', 'Policy name')}<label className="checkbox"><input type="checkbox" checked={values.is_default === true} onChange={(event) => set('is_default', event.target.checked)} /><span>Default policy</span></label></>}
    {editor.kind === 'escalation-step' && <><label>Policy<select required value={String(values.policy || '')} onChange={(event) => set('policy', event.target.value)}><option value="">Select policy</option>{policies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{common('level', 'Escalation level', 'number')}{common('delay_minutes', 'Delay in minutes', 'number')}<label>Channel<select value={String(values.channel || 'IN_APP')} onChange={(event) => set('channel', event.target.value)}><option value="IN_APP">In app</option><option value="PUSH">Push</option><option value="SMS">SMS</option><option value="VOICE">Voice call</option></select></label>{common('recipient_roles', 'Recipient roles (comma-separated)', 'text', false)}</>}
    {editor.kind === 'interaction' && <>{common('medication_a', 'Medication A')}{common('medication_b', 'Medication B')}<label>Severity<select value={String(values.severity || 'WARNING')} onChange={(event) => set('severity', event.target.value)}><option value="INFO">Information</option><option value="WARNING">Warning</option><option value="SEVERE">Severe</option></select></label>{common('message', 'Warning message')}{common('source', 'Evidence source')}</>}
    {editor.kind === 'task-template' && <>{common('name', 'Template name')}{common('title', 'Task title')}<label>Category<select value={String(values.category || 'PERSONAL_CARE')} onChange={(event) => set('category', event.target.value)}><option value="PERSONAL_CARE">Personal care</option><option value="HEALTH">Health</option><option value="MEAL">Meal</option><option value="ACTIVITY">Activity</option><option value="MEDICATION">Medication support</option><option value="OTHER">Other</option></select></label><label>Priority<select value={String(values.priority || 'NORMAL')} onChange={(event) => set('priority', event.target.value)}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label>{common('instructions', 'Care instructions')}{common('expected_outcome', 'Expected outcome', 'text', false)}{common('safety_notes', 'Safety notes', 'text', false)}{common('equipment', 'Equipment (comma-separated)', 'text', false)}<div className="form-row"><label>Frequency<select value={String(values.frequency || 'DAILY')} onChange={(event) => set('frequency', event.target.value)}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="ONCE">One time</option><option value="INTERVAL">Interval</option></select></label>{common('time', 'Default time', 'time')}</div></>}
    {editor.kind === 'organization' && <>{common('name', 'Organization name')}{common('slug', 'Slug')}{common('country_code', 'Country code', 'text', false)}{common('timezone', 'IANA timezone')}</>}
    {error && <div className="login-error"><AlertTriangle />{error}</div>}<button className="primary-button">Save</button></form></div>
}
