import { FormEvent, useCallback, useEffect, useState, type ReactNode } from 'react'
import { AlertTriangle, ClipboardList, FileCheck2, FileText, HeartPulse, Pencil, Phone, Plus, RefreshCw, ShieldAlert, Stethoscope, X } from 'lucide-react'

import { PageHeader } from '../components/PageHeader'
import { downloadClinicalDocument, getClinicalProfile, saveClinicalRecord } from '../lib/api'
import type { AdvanceDirective, Allergy, CarePlan, ClinicalDocument, Diagnosis, EmergencyContact, Patient, Session, VitalThreshold, WoundRecord } from '../lib/types'

type Profile = { allergies: Allergy[]; diagnoses: Diagnosis[]; carePlans: CarePlan[]; contacts: EmergencyContact[]; directives: AdvanceDirective[]; documents: ClinicalDocument[]; wounds: WoundRecord[]; thresholds: VitalThreshold[] }
type Kind = 'allergy' | 'diagnosis' | 'care-plan' | 'contact' | 'directive' | 'wound' | 'threshold'
type Editor = { kind: Kind; id: number | null; values: Record<string, string | boolean> }
const empty: Profile = { allergies: [], diagnoses: [], carePlans: [], contacts: [], directives: [], documents: [], wounds: [], thresholds: [] }
const paths: Record<Kind, string> = { allergy: 'allergies', diagnosis: 'diagnoses', 'care-plan': 'care-plans', contact: 'emergency-contacts', directive: 'advance-directives', wound: 'wound-records', threshold: 'vital-thresholds' }

export default function ClinicalProfileView({ session, patient, locale }: { session: Session; patient: Patient; locale: string }) {
  const fa = locale === 'fa'
  const t = fa ? { eyebrow: 'پرونده طولی', title: 'پرونده بالینی', description: `برنامه‌های مراقبتی، سوابق ایمنی، مخاطبان، دستورهای پیشین، زخم‌ها، آستانه‌ها و منشأ برای ${patient.full_name}.`, addRecord: 'افزودن رکورد', retry: 'تلاش دوباره', loading: 'در حال بارگذاری پرونده بالینی', allergies: 'حساسیت‌ها و موارد منع مصرف', diagnoses: 'تشخیص‌ها', plans: 'برنامه‌های مراقبتی', contacts: 'مخاطبان اضطراری و خانواده', directives: 'دستورهای پیشین', wounds: 'سوابق زخم', thresholds: 'آستانه‌های علائم حیاتی', documents: 'اسناد امن' } : { eyebrow: 'LONGITUDINAL RECORD', title: 'Clinical profile', description: `Care plans, safety records, contacts, directives, wounds, thresholds, and provenance for ${patient.full_name}.`, addRecord: 'Add record', retry: 'Try again', loading: 'Loading clinical record', allergies: 'Allergies & contraindications', diagnoses: 'Diagnoses', plans: 'Care plans', contacts: 'Emergency & family contacts', directives: 'Advance directives', wounds: 'Wound records', thresholds: 'Clinician vital thresholds', documents: 'Secure documents' }
  const [profile, setProfile] = useState<Profile>(empty)
  const [editor, setEditor] = useState<Editor | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const canEdit = ['ADMIN', 'DOCTOR'].includes(session.user.role)
  const load = useCallback(async () => { setLoading(true); setError(''); try { setProfile(await getClinicalProfile(session.token, patient.id)) } catch { setError('Clinical records could not be loaded.') } finally { setLoading(false) } }, [patient.id, session.token])
  useEffect(() => { load() }, [load])
  const edit = (kind: Kind, item?: Record<string, unknown>) => setEditor({ kind, id: Number(item?.id) || null, values: Object.fromEntries(Object.entries(item || {}).map(([key, value]) => [key, Array.isArray(value) ? value.join('\n') : value == null ? '' : value])) as Record<string, string | boolean> })
  const save = async (next: Editor) => {
    const values: Record<string, unknown> = { ...next.values, patient: patient.id }
    if (next.kind === 'care-plan') values.goals = String(values.goals || '').split('\n').map((item) => item.trim()).filter(Boolean)
    for (const key of ['minimum', 'maximum', 'secondary_minimum', 'secondary_maximum', 'length_cm', 'width_cm']) if (values[key] === '') values[key] = null
    await saveClinicalRecord(session.token, paths[next.kind], next.id, values); setEditor(null); await load()
  }
  const action = canEdit ? <button className="primary-button" onClick={() => edit('allergy')}><Plus />{t.addRecord}</button> : undefined
  const editButton = (kind: Kind, item: object) => canEdit && <button className="text-button" onClick={() => edit(kind, item as Record<string, unknown>)}><Pencil />Edit</button>
  return <><PageHeader eyebrow={t.eyebrow} title={t.title} description={t.description} action={action} />
    {error && <div className="workspace-notice"><AlertTriangle />{error}<button onClick={load}>{t.retry}</button></div>}{loading && <div className="empty-care"><RefreshCw className="spinning" /><strong>{t.loading}</strong></div>}
    <div className="clinical-grid">
      <Section title={t.allergies} icon={<ShieldAlert />} empty={!profile.allergies.length} onAdd={canEdit ? () => edit('allergy') : undefined}>{profile.allergies.map((item) => <article key={item.id}><AlertTriangle /><span><strong>{item.substance}</strong><small>{item.severity} · {item.reaction || 'Reaction not documented'} · source: {item.source_system || 'Haven'}</small></span>{editButton('allergy', item)}</article>)}</Section>
      <Section title={t.diagnoses} icon={<Stethoscope />} empty={!profile.diagnoses.length} onAdd={canEdit ? () => edit('diagnosis') : undefined}>{profile.diagnoses.map((item) => <article key={item.id}><Stethoscope /><span><strong>{item.display}</strong><small>{item.status}{item.code ? ` · ${item.code}` : ''} · source: {item.source_system || 'Haven'}</small></span>{editButton('diagnosis', item)}</article>)}</Section>
      <Section title={t.plans} icon={<ClipboardList />} empty={!profile.carePlans.length} wide onAdd={canEdit ? () => edit('care-plan') : undefined}>{profile.carePlans.map((item) => <article key={item.id}><ClipboardList /><span><strong>{item.title}</strong><small>{item.status} · {item.author_name}</small><p>{item.instructions}</p></span>{editButton('care-plan', item)}</article>)}</Section>
      <Section title={t.contacts} icon={<Phone />} empty={!profile.contacts.length} onAdd={canEdit ? () => edit('contact') : undefined}>{profile.contacts.map((item) => <article key={item.id}><Phone /><span><strong>{item.name}</strong><small>{item.relationship} · {item.phone}</small></span>{editButton('contact', item)}</article>)}</Section>
      <Section title={t.directives} icon={<FileCheck2 />} empty={!profile.directives.length} onAdd={canEdit ? () => edit('directive') : undefined}>{profile.directives.map((item) => <article key={item.id}><FileCheck2 /><span><strong>{item.directive_type}</strong><p>{item.summary}</p></span>{editButton('directive', item)}</article>)}</Section>
      <Section title={t.wounds} icon={<HeartPulse />} empty={!profile.wounds.length} onAdd={session.user.role !== 'FAMILY' ? () => edit('wound') : undefined}>{profile.wounds.map((item) => <article key={item.id}><HeartPulse /><span><strong>{item.location}</strong><small>{item.length_cm || '—'} × {item.width_cm || '—'} cm · {new Date(item.recorded_at).toLocaleString(fa ? 'fa-IR-u-ca-persian' : undefined)}</small><p>{item.description}</p></span>{session.user.role !== 'FAMILY' && <button className="text-button" onClick={() => edit('wound', item as unknown as Record<string, unknown>)}><Pencil />Edit</button>}</article>)}</Section>
      <Section title={t.thresholds} icon={<HeartPulse />} empty={!profile.thresholds.length} onAdd={canEdit ? () => edit('threshold') : undefined}>{profile.thresholds.map((item) => <article key={item.id}><HeartPulse /><span><strong>{item.vital_type.replace('_', ' ')}</strong><small>{item.minimum || '—'} to {item.maximum || '—'} · {item.severity}</small></span>{editButton('threshold', item)}</article>)}</Section>
      <Section title={t.documents} icon={<FileText />} empty={!profile.documents.length} wide>{profile.documents.map((item) => <button className="secure-document" onClick={() => downloadClinicalDocument(session.token, item.id)} key={item.id}><FileText /><span><strong>{item.title}</strong><small>{item.category} · source: {item.source_system || 'Haven'} · retained until {item.retention_until || 'policy review'}</small></span></button>)}</Section>
    </div>{editor && <ClinicalEditor locale={locale} editor={editor} onClose={() => setEditor(null)} onSave={save} />}</>
}

function Section({ title, icon, empty, wide, onAdd, children }: { title: string; icon: ReactNode; empty: boolean; wide?: boolean; onAdd?: () => void; children: ReactNode }) {
  return <section className={`main-card clinical-section ${wide ? 'wide' : ''}`}><h3>{icon}{title}{onAdd && <button className="text-button" onClick={onAdd}><Plus />Add</button>}</h3>{children}{empty && <p>No records documented.</p>}</section>
}

function ClinicalEditor({ editor, onClose, onSave, locale }: { editor: Editor; onClose: () => void; onSave: (value: Editor) => Promise<void>; locale: string }) {
  const fa = locale === 'fa'
  const [values, setValues] = useState(editor.values)
  const [error, setError] = useState('')
  const set = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }))
  const fields: Record<Kind, [string, string, string][]> = {
    allergy: [['substance', fa ? 'ماده حساسیت‌زا' : 'Substance', 'text'], ['reaction', fa ? 'واکنش' : 'Reaction', 'textarea'], ['severity', fa ? 'شدت (MILD، MODERATE، SEVERE، LIFE_THREATENING)' : 'Severity (MILD, MODERATE, SEVERE, LIFE_THREATENING)', 'text']],
    diagnosis: [['display', fa ? 'تشخیص' : 'Diagnosis', 'text'], ['code', fa ? 'کد بالینی' : 'Clinical code', 'text'], ['status', fa ? 'وضعیت (ACTIVE، RESOLVED، INACTIVE)' : 'Status (ACTIVE, RESOLVED, INACTIVE)', 'text'], ['notes', fa ? 'یادداشت‌ها' : 'Notes', 'textarea']],
    'care-plan': [['title', fa ? 'عنوان برنامه' : 'Plan title', 'text'], ['status', fa ? 'وضعیت (DRAFT، ACTIVE، ON_HOLD، COMPLETED)' : 'Status (DRAFT, ACTIVE, ON_HOLD, COMPLETED)', 'text'], ['goals', fa ? 'هدف‌ها (هر کدام در یک خط)' : 'Goals (one per line)', 'textarea'], ['instructions', fa ? 'دستورها' : 'Instructions', 'textarea']],
    contact: [['name', fa ? 'نام' : 'Name', 'text'], ['relationship', fa ? 'نسبت' : 'Relationship', 'text'], ['phone', fa ? 'تلفن' : 'Phone', 'tel'], ['email', fa ? 'ایمیل' : 'Email', 'email'], ['priority', fa ? 'اولویت' : 'Priority', 'number']],
    directive: [['directive_type', fa ? 'نوع دستور' : 'Directive type', 'text'], ['summary', fa ? 'خلاصه' : 'Summary', 'textarea'], ['effective_from', fa ? 'تاریخ اجرا' : 'Effective date', 'date']],
    wound: [['location', fa ? 'محل' : 'Location', 'text'], ['description', fa ? 'شرح' : 'Description', 'textarea'], ['length_cm', fa ? 'طول (سانتی‌متر)' : 'Length (cm)', 'number'], ['width_cm', fa ? 'عرض (سانتی‌متر)' : 'Width (cm)', 'number'], ['recorded_at', fa ? 'زمان ثبت' : 'Recorded at', 'datetime-local']],
    threshold: [['vital_type', fa ? 'نوع علامت حیاتی' : 'Vital type', 'text'], ['minimum', fa ? 'حداقل' : 'Minimum', 'number'], ['maximum', fa ? 'حداکثر' : 'Maximum', 'number'], ['secondary_minimum', fa ? 'حداقل دوم' : 'Secondary minimum', 'number'], ['secondary_maximum', fa ? 'حداکثر دوم' : 'Secondary maximum', 'number'], ['severity', fa ? 'شدت (WARNING یا CRITICAL)' : 'Severity (WARNING or CRITICAL)', 'text'], ['consecutive_readings', fa ? 'تعداد خوانش‌های پیاپی' : 'Consecutive readings', 'number']],
  }
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await onSave({ ...editor, values }) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : fa ? 'رکورد ذخیره نشد.' : 'Record could not be saved.') } }
  return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose} aria-label={fa ? 'بستن ویرایشگر پرونده بالینی' : 'Close clinical editor'} /><form className="modal task-form" role="dialog" aria-modal="true" aria-label={fa ? 'ویرایشگر پرونده بالینی' : 'Clinical record editor'} onSubmit={submit}><button type="button" className="modal-close" onClick={onClose} aria-label={fa ? 'بستن' : 'Close'}><X /></button><span className="eyebrow">{fa ? 'رکورد بالینی' : 'CLINICAL RECORD'}</span><h2>{editor.id ? (fa ? 'ویرایش' : 'Edit') : (fa ? 'افزودن' : 'Add')} {fa ? ({ allergy: 'حساسیت', diagnosis: 'تشخیص', 'care-plan': 'برنامه مراقبتی', contact: 'مخاطب', directive: 'دستور پیشین', wound: 'رکورد زخم', threshold: 'آستانه' }[editor.kind]) : editor.kind.replace('-', ' ')}</h2>{fields[editor.kind].map(([key, label, type]) => <label key={key}>{label}{type === 'textarea' ? <textarea required={['reaction'].includes(key) === false && ['notes', 'goals'].includes(key) === false} value={String(values[key] ?? '')} onChange={(event) => set(key, event.target.value)} /> : <input dir={type.includes('date') ? 'ltr' : undefined} type={type} step={type === 'number' ? 'any' : undefined} required={!['code', 'email', 'effective_from', 'length_cm', 'width_cm', 'secondary_minimum', 'secondary_maximum'].includes(key)} value={String(values[key] ?? '')} onChange={(event) => set(key, event.target.value)} />}</label>)}{editor.kind === 'contact' && <label className="checkbox"><input type="checkbox" checked={Boolean(values.authorized_for_updates)} onChange={(event) => set('authorized_for_updates', event.target.checked)} /><span>{fa ? 'مجاز برای دریافت به‌روزرسانی' : 'Authorized for updates'}</span></label>}{error && <div className="login-error"><AlertTriangle />{error}</div>}<button className="primary-button">{fa ? 'ذخیره رکورد بالینی' : 'Save clinical record'}</button></form></div>
}
