import { useCallback, useEffect, useState } from 'react'
import { AlertCircle, CheckCircle2, FileText, HeartPulse, Printer, RefreshCw, Send, Sun } from 'lucide-react'

import { PageHeader } from '../components/PageHeader'
import { acknowledgeReport, getReports, getShifts, transitionShift } from '../lib/api'
import type { Patient, Session, ShiftAssignment, ShiftReport } from '../lib/types'

export default function ReportsView({ session, patient, taskCount, vitalCount, onSend, notify, canAuthor = true, locale = 'en' }: { session: Session; patient: Patient; taskCount: number; vitalCount: number; onSend: (observations: string, concerns: string) => Promise<void>; notify: (message: string) => void; canAuthor?: boolean; locale?: string }) {
  const fa = locale === 'fa'
  const t = fa ? { eyebrow: 'تداوم مراقبت', title: 'گزارش‌ها و تحویل شیفت', description: 'تاریخچه، تأیید و مسئولیت واقعی شیفت.', retry: 'تلاش دوباره', current: 'شیفت فعلی', handover: 'تحویل شیفت', tasks: 'وظایف انجام‌شده', issues: 'موارد گزارش‌شده', vitals: 'علائم ثبت‌شده', observations: 'مشاهدات', observationsPlaceholder: 'مراقب بعدی چه چیزی باید بداند؟', concerns: 'نگرانی‌ها یا پیگیری', sending: 'در حال ارسال…', send: 'ارسال تحویل شیفت', next: 'شیفت بعدی', noShift: 'شیفت پیش‌رو وجود ندارد', accept: 'پذیرش شیفت', checkIn: 'شروع شیفت', checkOut: 'پایان شیفت', readonly: 'نمای فقط‌خواندنی خانواده', readonlyDetail: 'تحویل‌گیری‌های تیم مراقبت در اینجا قابل بررسی و تأیید است.', history: 'تاریخچه گزارش‌ها', loading: 'در حال بارگذاری تحویل‌ها', concern: 'نگرانی', acknowledged: 'تأیید شده توسط', acknowledge: 'تأیید', none: 'هنوز تحویل شیفتی ثبت نشده است' } : { eyebrow: 'CARE CONTINUITY', title: 'Reports & handovers', description: 'History, acknowledgement, and real shift ownership.', retry: 'Try again', current: 'CURRENT SHIFT', handover: 'Shift handover', tasks: 'Tasks complete', issues: 'Issues reported', vitals: 'Vitals recorded', observations: 'Observations', observationsPlaceholder: 'What should the next caregiver know?', concerns: 'Concerns or follow-up', sending: 'Sending…', send: 'Send handover', next: 'NEXT ASSIGNMENT', noShift: 'No upcoming shift', accept: 'Accept shift', checkIn: 'Check in', checkOut: 'Check out', readonly: 'Read-only family view', readonlyDetail: 'Care-team handovers can be reviewed and acknowledged here.', history: 'Report history', loading: 'Loading handovers', concern: 'Concern', acknowledged: 'Acknowledged by', acknowledge: 'Acknowledge', none: 'No handovers yet' }
  const [observations, setObservations] = useState('')
  const [concerns, setConcerns] = useState('')
  const [handoverChecks, setHandoverChecks] = useState({ incomplete: false, medication: false })
  const [reports, setReports] = useState<ShiftReport[]>([])
  const [shifts, setShifts] = useState<ShiftAssignment[]>([])
  const [sending, setSending] = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = useCallback(async () => {
    setLoading(true); setError('')
    try {
      const [nextReports, nextShifts] = await Promise.all([getReports(session.token, patient.id), getShifts(session.token, patient.id)])
      setReports(nextReports); setShifts(nextShifts)
    } catch { setError('Handover history could not be loaded.') }
    finally { setLoading(false) }
  }, [patient.id, session.token])
  useEffect(() => { load() }, [load])
  const submit = async () => { setSending(true); setError(''); try { await onSend(observations, concerns); setObservations(''); setConcerns(''); await load() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Handover could not be sent.') } finally { setSending(false) } }
  const acknowledge = async (id: number) => { await acknowledgeReport(session.token, id); await load(); notify(fa ? 'تحویل شیفت تأیید شد' : 'Handover acknowledged') }
  const moveShift = async (shift: ShiftAssignment, action: 'accept' | 'check_in' | 'check_out') => { await transitionShift(session.token, shift.id, action); await load(); notify(fa ? 'وضعیت شیفت ثبت شد' : `Shift ${action.replace('_', ' ')} recorded`) }
  const nextShift = shifts.find((shift) => new Date(shift.ends_at) > new Date())
  return <><PageHeader eyebrow={t.eyebrow} title={t.title} description={t.description} action={<button className="secondary-button print-report-button" onClick={() => window.print()}><Printer />{fa ? 'چاپ گزارش' : 'Print report'}</button>} />
    {error && <div className="workspace-notice"><AlertCircle />{error}<button className="text-button" onClick={load}>{t.retry}</button></div>}
    {canAuthor ? <div className="reports-grid"><section className="main-card report-composer"><span className="eyebrow"><Sun size={16} /> {t.current}</span><h2>{t.handover}</h2><div className="report-stats"><div><CheckCircle2 /><strong>{taskCount}</strong><span>{t.tasks}</span></div><div><AlertCircle /><strong>{concerns ? 1 : 0}</strong><span>{t.issues}</span></div><div><HeartPulse /><strong>{vitalCount}</strong><span>{t.vitals}</span></div></div><label>{t.observations}<textarea value={observations} onChange={(event) => setObservations(event.target.value)} placeholder={t.observationsPlaceholder} /></label><label>{t.concerns}<textarea value={concerns} onChange={(event) => setConcerns(event.target.value)} /></label><fieldset className="verification-list handover-checklist"><legend>{fa ? 'پیش از ارسال تأیید کنید' : 'Confirm before sending'}</legend><label className="verification-check"><input type="checkbox" checked={handoverChecks.incomplete} onChange={(event) => setHandoverChecks((value) => ({ ...value, incomplete: event.target.checked }))} /><span>{fa ? 'وظایف ناتمام و سررسیدشده را بررسی کردم.' : 'I reviewed incomplete and overdue care tasks.'}</span></label><label className="verification-check"><input type="checkbox" checked={handoverChecks.medication} onChange={(event) => setHandoverChecks((value) => ({ ...value, medication: event.target.checked }))} /><span>{fa ? 'موارد دارویی و پیگیری‌های ضروری را بررسی کردم.' : 'I reviewed medication issues and required follow-up.'}</span></label></fieldset><button className="primary-button" onClick={submit} disabled={sending || !observations.trim() || !handoverChecks.incomplete || !handoverChecks.medication}><Send />{sending ? t.sending : t.send}</button></section><aside><div className="side-card next-caregiver"><span className="eyebrow">{t.next}</span><h3>{nextShift?.caregiver_name || t.noShift}</h3>{nextShift && <><p>{new Date(nextShift.starts_at).toLocaleString(fa ? 'fa-IR-u-ca-persian' : undefined)}–{new Date(nextShift.ends_at).toLocaleTimeString(fa ? 'fa-IR-u-ca-persian' : undefined)}</p>{nextShift.caregiver === session.user.id && <div className="med-actions">{nextShift.status === 'SCHEDULED' && <button className="primary-button" onClick={() => moveShift(nextShift, 'accept')}>{t.accept}</button>}{nextShift.status === 'ACCEPTED' && <button className="primary-button" onClick={() => moveShift(nextShift, 'check_in')}>{t.checkIn}</button>}{nextShift.status === 'IN_PROGRESS' && <button className="primary-button" onClick={() => moveShift(nextShift, 'check_out')}>{t.checkOut}</button>}</div>}</>}</div></aside></div> : <div className="role-context"><FileText /><strong>{t.readonly}</strong><span>{t.readonlyDetail}</span></div>}
    <section className="main-card recent-readings"><div className="subsection-heading"><h3>{t.history}</h3></div>{loading && <div className="empty-care compact"><RefreshCw className="spinning" /><strong>{t.loading}</strong></div>}{reports.map((report) => <article className="audit-row" key={report.id}><FileText /><div><strong>{report.author_name}</strong><p>{report.observations}</p>{report.concerns && <small>{t.concern}: {report.concerns}</small>}<small>{new Date(report.created_at).toLocaleString(fa ? 'fa-IR-u-ca-persian' : undefined)}</small></div>{report.acknowledged_at ? <b>{t.acknowledged} {report.acknowledged_by_name}</b> : <button className="secondary-button" onClick={() => acknowledge(report.id)}>{t.acknowledge}</button>}</article>)}{!loading && !reports.length && <div className="empty-care compact"><FileText /><strong>{t.none}</strong></div>}</section></>
}
