import { useCallback, useEffect, useState } from 'react'
import { Bell, ChevronRight, KeyRound, Languages, LogOut, MonitorSmartphone, ShieldCheck, Trash2 } from 'lucide-react'
import { confirmMfa, enableWebPush, getNotificationPreference, getSessions, revokeOtherSessions, revokeSession, setupMfa, updateNotificationPreference } from '../lib/api'
import { clearOfflineData } from '../lib/offline'
import type { DeviceSession, NotificationPreference, Session } from '../lib/types'
import { PageHeader } from '../components/PageHeader'

function initials(name: string) { return name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase() }

export default function SettingsView({ session, onSignOut, notify, locale, onLocale }: { session: Session; onSignOut: () => void; notify: (message: string) => void; locale: string; onLocale: (value: string) => void }) {
  const [preference, setPreference] = useState<NotificationPreference | null>(null)
  const [sessions, setSessions] = useState<DeviceSession[]>([])
  const [mfaSecret, setMfaSecret] = useState('')
  const [mfaCode, setMfaCode] = useState('')
  const [mfaEnabled, setMfaEnabled] = useState(session.user.mfa_enabled)
  const load = useCallback(() => Promise.all([getNotificationPreference(session.token), getSessions(session.token)]).then(([nextPreference, nextSessions]) => { setPreference(nextPreference); setSessions(nextSessions) }), [session.token])
  useEffect(() => { load().catch(() => notify('Some settings could not be loaded')) }, [load, notify])
  const patchPreference = async (values: Partial<NotificationPreference>) => { const next = await updateNotificationPreference(session.token, values); setPreference(next); notify('Notification preferences saved') }
  const startMfa = async () => { const result = await setupMfa(session.token); setMfaSecret(result.secret) }
  const finishMfa = async () => { await confirmMfa(session.token, mfaCode); setMfaEnabled(true); setMfaSecret(''); setMfaCode(''); notify('Multi-factor authentication enabled') }
  return <><PageHeader eyebrow="YOUR WORKSPACE" title="Settings" description="Delivery preferences, security, devices, language, and offline privacy." /><div className="settings-layout"><section className="main-card settings-card"><h3>Profile</h3><div className="profile-settings"><div className="avatar avatar-sarah large-avatar">{initials(session.user.display_name)}</div><div><strong>{session.user.display_name}</strong><span>{session.user.role.toLowerCase()} · {session.user.organization_name || 'Independent care'}</span><small>Session expires {new Date(session.expires_at).toLocaleString()}</small></div></div><hr />
    <h3>Background notification delivery</h3><button className="settings-row" onClick={async () => { try { await enableWebPush(session.token); await patchPreference({ push_enabled: true }); notify('Background Web Push enabled on this device') } catch (error) { notify(error instanceof Error ? error.message : 'Push setup failed') } }}><Bell /><span><strong>Enable Web Push</strong><small>Receive alerts through the service worker when Haven is closed.</small></span><ChevronRight /></button>{preference && <><Toggle title="SMS escalation" detail="Allow critical missed-care escalation by text." checked={preference.sms_enabled} onChange={(sms_enabled) => patchPreference({ sms_enabled })} /><Toggle title="Phone escalation" detail="Allow critical escalation by automated call." checked={preference.voice_enabled} onChange={(voice_enabled) => patchPreference({ voice_enabled })} /><Toggle title="Critical quiet-hours override" detail="Critical medication alerts can break quiet hours." checked={preference.critical_override} onChange={(critical_override) => patchPreference({ critical_override })} /><div className="form-row"><label>Quiet hours start<input type="time" value={preference.quiet_hours_start?.slice(0, 5) || ''} onChange={(event) => patchPreference({ quiet_hours_start: event.target.value || null })} /></label><label>Quiet hours end<input type="time" value={preference.quiet_hours_end?.slice(0, 5) || ''} onChange={(event) => patchPreference({ quiet_hours_end: event.target.value || null })} /></label></div></>}
    <hr /><h3>Multi-factor authentication</h3>{mfaEnabled ? <div className="secure-note"><ShieldCheck /> MFA is enabled for this account.</div> : mfaSecret ? <div className="mfa-setup"><p>Add this setup key to an authenticator app:</p><code>{mfaSecret}</code><label>Six-digit verification code<input inputMode="numeric" value={mfaCode} onChange={(event) => setMfaCode(event.target.value)} /></label><button className="primary-button" onClick={finishMfa}>Verify and enable</button></div> : <button className="settings-row" onClick={startMfa}><KeyRound /><span><strong>Set up authenticator MFA</strong><small>Require a rotating code at sign-in.</small></span><ChevronRight /></button>}
    <hr /><h3>Language & direction</h3><button className="settings-row" onClick={() => onLocale(locale === 'fa' ? 'en' : 'fa')}><Languages /><span><strong>{locale === 'fa' ? 'Switch to English' : 'فارسی و راست‌به‌چپ'}</strong><small>Locale-aware dates and a right-to-left interface.</small></span><ChevronRight /></button>
    <hr /><h3>Active devices</h3><button className="secondary-button" onClick={async () => { const result = await revokeOtherSessions(session.token); await load(); notify(`${result.revoked} other sessions revoked`) }}>Revoke all other devices</button>{sessions.map((item) => <div className="settings-row" key={item.id}><MonitorSmartphone /><span><strong>{item.device_name || 'Browser session'}{item.id === session.session_id ? ' · This device' : ''}</strong><small>{item.active ? `Active · expires ${new Date(item.expires_at).toLocaleDateString()}` : 'Revoked or expired'}</small></span>{item.active && item.id !== session.session_id && <button className="text-button danger-text" onClick={async () => { await revokeSession(session.token, item.id); await load() }}>Revoke</button>}</div>)}
    <hr /><h3>Offline privacy</h3><button className="settings-row" onClick={async () => { await clearOfflineData(); notify('Offline care data removed from this device') }}><Trash2 /><span><strong>Erase offline data</strong><small>Cached records expire automatically and can be removed now.</small></span><ChevronRight /></button>
    </section><aside className="side-card signout-card"><LogOut /><h3>End your session</h3><p>Remote revocation and expiry protect lost or shared devices.</p><button className="danger-button" onClick={onSignOut}>Sign out</button></aside></div></>
}

function Toggle({ title, detail, checked, onChange }: { title: string; detail: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <button className="toggle-row" role="switch" aria-checked={checked} onClick={() => onChange(!checked)}><span><strong>{title}</strong><small>{detail}</small></span><i className={checked ? 'on' : ''}><b /></i></button>
}
