import { AlertCircle, CheckCircle2, Cloud, CloudOff, Clock3, Pill, ShieldCheck, UserRound } from 'lucide-react'

import { PageHeader } from '../components/PageHeader'
import { copy } from '../lib/i18n'
import type { DoseLog, Patient } from '../lib/types'

type ShiftTask = { id: number; title: string; time: string; detail: string; status: 'done' | 'overdue' | 'now' | 'upcoming'; category: 'medication' | 'health' | 'meal' | 'activity' | 'care' }

export default function ShiftModeView({ patient, tasks, doses, offline, pending, locale, onTask, onDose }: { patient: Patient; tasks: ShiftTask[]; doses: DoseLog[]; offline: boolean; pending: number; locale: string; onTask: (task: ShiftTask) => void; onDose: (dose: DoseLog) => void }) {
  const t = copy(locale).shift
  const due = tasks.filter((task) => task.status === 'now' || task.status === 'overdue')
  const pendingDoses = doses.filter((dose) => dose.status === 'SCHEDULED')
  const next = tasks.filter((task) => task.status === 'upcoming').slice(0, 4)
  return <><PageHeader eyebrow={t.eyebrow} title={t.title} description={t.description} /><section className="mobile-shift-mode"><div className="shift-patient-lockup"><span className="patient-photo">{patient.photo ? <img src={patient.photo} alt="" /> : <UserRound />}</span><span><small>{t.patient}</small><strong>{patient.full_name}</strong><b>{patient.room ? `${t.room} ${patient.room}` : patient.age}</b></span><span className={`shift-sync ${offline ? 'offline' : ''}`}>{offline ? <CloudOff /> : <Cloud />} {offline ? t.offline : pending ? `${pending} ${t.pending}` : t.synced}</span></div><div className="shift-priority-grid"><section><div className="shift-section-title"><AlertCircle /><h2>{t.due}</h2><b>{due.length}</b></div>{due.map((task) => <button className={`shift-action-card ${task.status}`} key={task.id} onClick={() => onTask(task)}><time dir="ltr">{task.time}</time><span><strong>{task.title}</strong><small>{task.detail}</small></span><span>{t.record}</span></button>)}{!due.length && <div className="shift-empty"><CheckCircle2 /><strong>{t.none}</strong><p>{t.noneDetail}</p></div>}</section><section><div className="shift-section-title"><Pill /><h2>{t.medications}</h2><b>{pendingDoses.length}</b></div>{pendingDoses.map((dose) => <button className="shift-action-card medication" key={dose.id} onClick={() => onDose(dose)}><time dir="ltr">{new Date(dose.scheduled_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time><span><strong>{dose.medication_name}</strong><small>{Number(dose.dose)} {dose.unit} · {dose.route}</small></span><span>{t.verify}</span></button>)}{!pendingDoses.length && <div className="shift-empty"><ShieldCheck /><strong>{t.noMedication}</strong></div>}</section></div><section className="main-card shift-next-list"><div className="shift-section-title"><Clock3 /><h2>{t.upcoming}</h2></div>{next.map((task) => <button key={task.id} onClick={() => onTask(task)}><time dir="ltr">{task.time}</time><span><strong>{task.title}</strong><small>{task.detail}</small></span></button>)}</section></section></>
}
