# Generated by Django 5.2.4 on 2026-07-16 12:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginattempt_organization_user_mfa_confirmed_at_and_more"),
        ("safety", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("last_seen_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name="carenotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TASK_OVERDUE", "Task overdue"),
                    ("DOSE_OVERDUE", "Medication overdue"),
                    ("SYNC_CONFLICT", "Sync conflict"),
                    ("VITAL_ALERT", "Vital threshold alert"),
                    ("URGENT_MESSAGE", "Urgent message"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="EscalationPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="escalation_policies", to="accounts.organization"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("voice_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("critical_override", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notification_preference", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.URLField(max_length=1000, unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("device_name", models.CharField(blank=True, max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("last_delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="push_subscriptions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalationStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveSmallIntegerField()),
                ("delay_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "channel",
                    models.CharField(
                        choices=[("IN_APP", "In-app"), ("PUSH", "Web push"), ("SMS", "SMS"), ("VOICE", "Voice call")], max_length=12
                    ),
                ),
                ("recipient_roles", models.JSONField(blank=True, default=list)),
                (
                    "policy",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="safety.escalationpolicy"),
                ),
            ],
            options={
                "ordering": ["level", "delay_minutes", "channel"],
                "constraints": [models.UniqueConstraint(fields=("policy", "level", "channel"), name="unique_escalation_policy_step")],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("IN_APP", "In-app"), ("PUSH", "Web push"), ("SMS", "SMS"), ("VOICE", "Voice call")], max_length=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted by provider"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("DEAD", "Dead letter"),
                            ("SUPPRESSED", "Suppressed by quiet hours or preference"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("destination_hint", models.CharField(blank=True, max_length=255)),
                ("provider_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "notification",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="safety.carenotification"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("notification", "channel"), name="unique_notification_delivery_channel")],
            },
        ),
    ]
