# Generated by Django 5.2.4 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("safety", "0002_workerheartbeat_alter_carenotification_kind_and_more")]

    operations = [
        migrations.AlterField(
            model_name="carenotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TASK_OVERDUE", "Task overdue"),
                    ("DOSE_OVERDUE", "Medication overdue"),
                    ("DOSE_TIMING_EXCEPTION", "Medication timing exception"),
                    ("SYNC_CONFLICT", "Sync conflict"),
                    ("VITAL_ALERT", "Vital threshold alert"),
                    ("URGENT_MESSAGE", "Urgent message"),
                ],
                max_length=24,
            ),
        ),
    ]
