# Generated by Django 5.2.4 on 2026-07-16 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("dose", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=32)),
                ("route", models.CharField(default="Oral", max_length=64)),
                ("instructions", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="medications/")),
                ("stock_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="medications", to="patients.patient"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time", models.TimeField()),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("instructions", models.CharField(blank=True, max_length=255)),
                (
                    "medication",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="medications.medication"),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="DoseLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("GIVEN", "Given"),
                            ("MISSED", "Missed"),
                            ("REFUSED", "Refused"),
                            ("HELD", "Held"),
                        ],
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                ("administered_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("client_reference", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_doses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dose_logs", to="medications.medication"),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
                "constraints": [models.UniqueConstraint(fields=("medication", "scheduled_at"), name="unique_medication_scheduled_dose")],
            },
        ),
    ]
