# Generated by Django 5.2.4 on 2026-07-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doselog",
            name="verified_dose",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doselog",
            name="verified_medication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doselog",
            name="verified_patient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doselog",
            name="verified_route",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doselog",
            name="verified_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doselog",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="DoseCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("GIVEN", "Given"),
                            ("MISSED", "Missed"),
                            ("REFUSED", "Refused"),
                            ("HELD", "Held"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "corrected_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("GIVEN", "Given"),
                            ("MISSED", "Missed"),
                            ("REFUSED", "Refused"),
                            ("HELD", "Held"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("client_reference", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="dose_corrections", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "dose_log",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corrections", to="medications.doselog"),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
