# Generated by Django 5.2.4 on 2026-07-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginattempt_organization_user_mfa_confirmed_at_and_more"),
        ("medications", "0002_doselog_verified_dose_doselog_verified_medication_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doselog",
            name="is_prn",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doselog",
            name="late_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doselog",
            name="was_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medication",
            name="approval_status",
            field=models.CharField(
                choices=[("PENDING", "Pending clinical approval"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                default="APPROVED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_medications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="barcode",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="medication",
            name="code_system",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="medication",
            name="ends_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="is_prn",
            field=models.BooleanField(default=False, help_text="Administer only as needed"),
        ),
        migrations.AddField(
            model_name="medication",
            name="max_daily_doses",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="medication_code",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="medication",
            name="prescriber",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="medication",
            name="prn_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medication",
            name="starts_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RefillRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("REQUESTED", "Requested"), ("ORDERED", "Ordered"), ("RECEIVED", "Received"), ("CANCELED", "Canceled")],
                        default="REQUESTED",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="refill_requests", to="medications.medication"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="refill_requests", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_refills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_delta", models.IntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("resulting_quantity", models.PositiveIntegerField()),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stock_adjustments", to="medications.medication"
                    ),
                ),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medication_a", models.CharField(max_length=160)),
                ("medication_b", models.CharField(max_length=160)),
                (
                    "severity",
                    models.CharField(choices=[("INFO", "Information"), ("WARNING", "Warning"), ("SEVERE", "Severe")], max_length=12),
                ),
                ("message", models.TextField()),
                ("source", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_interactions",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "medication_a", "medication_b"), name="unique_medication_interaction")
                ],
            },
        ),
    ]
