# Generated by Django 5.2.4 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0003_doselog_is_prn_doselog_late_minutes_doselog_was_late_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doselog",
            name="timing_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="doselog",
            name="timing_status",
            field=models.CharField(
                choices=[("ON_TIME", "On time"), ("EARLY", "Administered early"), ("LATE", "Administered late")],
                default="ON_TIME",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="doselog",
            name="timing_variance_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
