# Generated by Django 5.2.4 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0004_doselog_administration_timing"),
        ("safety", "0002_workerheartbeat_alter_carenotification_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="timing_escalation_level",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Highest organization escalation level used when this order is administered outside its timing window."
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="timing_escalation_policy",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional organization escalation chain for timing exceptions; the organization default is used when empty.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timing_escalation_medications",
                to="safety.escalationpolicy",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="timing_window_minutes",
            field=models.PositiveSmallIntegerField(
                default=30, help_text="Allowed minutes before or after the scheduled time before a timing exception is recorded."
            ),
        ),
        migrations.AddField(
            model_name="doselog",
            name="timing_window_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
