# Generated by Django 5.2.4 on 2026-07-16 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("FEMALE", "Female"), ("MALE", "Male"), ("OTHER", "Other"), ("UNDISCLOSED", "Prefer not to say")],
                        default="UNDISCLOSED",
                        max_length=16,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=64)),
                ("medical_notes", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="patients/")),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CareAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("PRIMARY_CAREGIVER", "Primary caregiver"),
                            ("CAREGIVER", "Caregiver"),
                            ("DOCTOR", "Doctor"),
                            ("FAMILY", "Family"),
                            ("ADMINISTRATOR", "Administrator"),
                        ],
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="care_assignments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="care_assignments", to="patients.patient"),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "patient"), name="unique_user_patient_assignment")],
            },
        ),
    ]
