# Generated by Django 5.2.4 on 2026-07-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginattempt_organization_user_mfa_confirmed_at_and_more"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="patients", to="accounts.organization"
            ),
        ),
    ]
