# Generated by Django 5.2.4 on 2026-07-16 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEDICATION", "Medication"),
                            ("HEALTH", "Health check"),
                            ("MEAL", "Meal"),
                            ("ACTIVITY", "Activity"),
                            ("PERSONAL_CARE", "Personal care"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="patients.patient")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskOccurrence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("MISSED", "Missed"),
                            ("SKIPPED", "Skipped"),
                            ("DELAYED", "Delayed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("delayed_until", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_task_occurrences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="occurrences", to="care_tasks.task")),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="CompletionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="task-completions/")),
                ("client_reference", models.UUIDField(blank=True, help_text="Idempotency key for offline sync", null=True, unique=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="task_completion_logs", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="completion", to="care_tasks.taskoccurrence"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONCE", "Once"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("INTERVAL", "Interval"),
                            ("AFTER_EVENT", "After event"),
                        ],
                        default="DAILY",
                        max_length=16,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("specific_date", models.DateField(blank=True, null=True)),
                ("interval_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("days_of_week", models.JSONField(blank=True, default=list, help_text="ISO weekday numbers, Monday=1")),
                ("event_reference", models.CharField(blank=True, max_length=120)),
                ("window_before_minutes", models.PositiveSmallIntegerField(default=0)),
                ("window_after_minutes", models.PositiveSmallIntegerField(default=30)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="care_tasks.task")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="taskoccurrence",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="care_tasks.taskschedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskoccurrence",
            constraint=models.UniqueConstraint(fields=("task", "scheduled_at"), name="unique_task_scheduled_occurrence"),
        ),
    ]
