# Generated by Django 5.2.4 on 2026-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="client_reference",
            field=models.UUIDField(blank=True, help_text="Idempotency key for offline creation", null=True, unique=True),
        ),
    ]
