# Generated by Django 5.2.4 on 2026-07-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_tasks", "0002_task_client_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="completionlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("PARTIAL", "Partially completed"),
                    ("UNABLE", "Unable to complete"),
                    ("REFUSED", "Patient refused"),
                ],
                default="COMPLETED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="taskoccurrence",
            name="outcome",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="taskoccurrence",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="CompletionCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("MISSED", "Missed"),
                            ("SKIPPED", "Skipped"),
                            ("DELAYED", "Delayed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "corrected_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("MISSED", "Missed"),
                            ("SKIPPED", "Skipped"),
                            ("DELAYED", "Delayed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("previous_outcome", models.CharField(blank=True, max_length=16)),
                ("corrected_outcome", models.CharField(blank=True, max_length=16)),
                ("reason", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("client_reference", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="task_completion_corrections", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="corrections", to="care_tasks.taskoccurrence"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
