# Generated by Django 5.2.4 on 2026-07-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginattempt_organization_user_mfa_confirmed_at_and_more"),
        ("care_tasks", "0003_completionlog_outcome_taskoccurrence_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="equipment",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="expected_outcome",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="requires_note",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="requires_photo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="safety_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="taskschedule",
            name="frequency",
            field=models.CharField(
                choices=[("ONCE", "Once"), ("DAILY", "Daily"), ("WEEKLY", "Weekly"), ("INTERVAL", "Interval")],
                default="DAILY",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CareTaskTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEDICATION", "Medication"),
                            ("HEALTH", "Health check"),
                            ("MEAL", "Meal"),
                            ("ACTIVITY", "Activity"),
                            ("PERSONAL_CARE", "Personal care"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("expected_outcome", models.TextField(blank=True)),
                ("safety_notes", models.TextField(blank=True)),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("schedule_defaults", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="care_task_templates", to="accounts.organization"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [models.UniqueConstraint(fields=("organization", "name"), name="unique_org_care_task_template")],
            },
        ),
    ]
