# Generated by Django 5.2.4 on 2026-08-17 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_tasks', '0005_caretasktemplate_completion_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskoccurrence',
            index=models.Index(fields=['status', 'scheduled_at'], name='task_occ_status_sched_idx'),
        ),
    ]
