# Generated by Django 5.2.4 on 2026-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_tasks", "0006_taskoccurrence_task_occ_status_sched_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="schedule_type",
            field=models.CharField(
                choices=[("SCHEDULED", "Scheduled"), ("ON_DEMAND", "On Demand (Quick Log)")],
                db_index=True,
                default="SCHEDULED",
                help_text="Scheduled tasks generate periodic occurrences; On-demand tasks are logged directly on the fly.",
                max_length=16,
            ),
        ),
    ]
