# Generated by Django 5.2.4 on 2026-09-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_allow_family_task_completion_and_more"),
        ("care_tasks", "0007_task_schedule_type"),
        ("patients", "0003_patient_organization_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdHocTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEDICATION", "Medication"),
                            ("HEALTH", "Health check"),
                            ("MEAL", "Meal"),
                            ("ACTIVITY", "Activity"),
                            ("PERSONAL_CARE", "Personal care"),
                            ("OTHER", "Other"),
                        ],
                        default="PERSONAL_CARE",
                        max_length=24,
                    ),
                ),
                ("icon", models.CharField(default="Sparkles", max_length=64)),
                ("color", models.CharField(blank=True, default="", max_length=64)),
                ("is_quick_action", models.BooleanField(db_index=True, default=True)),
                ("default_note", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("client_reference", models.UUIDField(blank=True, help_text="Idempotency key for offline sync", null=True, unique=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ad_hoc_templates", to="accounts.organization"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_hoc_templates",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.AddField(
            model_name="taskoccurrence",
            name="ad_hoc_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="care_tasks.adhoctemplate",
            ),
        ),
    ]
