# Generated by Django 5.2.4 on 2026-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_tasks", "0008_adhoctemplate_taskoccurrence_ad_hoc_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="adhoctemplate",
            name="requires_note",
            field=models.BooleanField(default=False),
        ),
    ]
