# Generated by Django 5.2.4 on 2026-07-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.clinical.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0002_patient_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(choices=[("CLINICAL", "Clinical"), ("FAMILY", "Family"), ("HANDOVER", "Handover")], max_length=16),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="created_conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("participants", models.ManyToManyField(related_name="care_conversations", to=settings.AUTH_USER_MODEL)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="patients.patient"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True)),
                ("clinical", models.BooleanField(default=False)),
                ("urgent", models.BooleanField(default=False)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to="message-attachments/", validators=[apps.clinical.models.validate_clinical_file]
                    ),
                ),
                (
                    "voice_note",
                    models.FileField(blank=True, upload_to="message-voice/", validators=[apps.clinical.models.validate_clinical_file]),
                ),
                ("client_reference", models.UUIDField(blank=True, null=True, unique=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="communications.conversation"
                    ),
                ),
                ("mentions", models.ManyToManyField(blank=True, related_name="mentioned_messages", to=settings.AUTH_USER_MODEL)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="care_messages", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACCEPTED", "Accepted"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shift_assignments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shift_assignments", to="patients.patient"),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="read_receipts", to="communications.message"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="message_read_receipts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("message", "user"), name="unique_message_read_receipt")],
            },
        ),
    ]
