# Generated by Django 5.2.4 on 2026-07-16 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("available", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="availability_windows", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("caregiver", "starts_at", "ends_at"), name="unique_caregiver_availability_window")
                ],
            },
        ),
    ]
